'use strict';

const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const { createSessionManager } = require('../session-manager');
const { createTicketsStore } = require('../tickets-store');
const { intentEnabled } = require('../intent-catalog');
const { mkTmpRoot } = require('./lib/tmp-roots');
const { pathFor, runDirFor } = require('../clodex-paths');
const { spillIdOf, SPILL_MIN_BYTES, SNAPSHOT_MAX_BYTES, capResumeSnapshot } = require('../intent-spill');
const gitWorktree = require('../git-worktree');

const AUTHOR = `pick up the thread:\n${'h'.repeat(1000)}\nnext: finish t9`;
const SHORT = 'pick up the thread: finish t9';
const SEP = '\n\n---\n';

function mkRepo(dir, subject = 'the base commit') {
  const run = (...args) => execFileSync('git', ['-C', dir, ...args], { stdio: ['ignore', 'pipe', 'ignore'] });
  run('init', '-q', '-b', 'master');
  run('config', 'user.email', 't@example.com');
  run('config', 'user.name', 'T');
  fs.writeFileSync(path.join(dir, 'f.txt'), 'x');
  run('add', 'f.txt');
  run('commit', '-q', '-m', subject);
  return String(execFileSync('git', ['-C', dir, 'rev-parse', '--short', 'HEAD'], { encoding: 'utf8' })).trim();
}

function mkSnap({ withTeam = true, repo = true, tickets = [], subject = 'the base commit' } = {}) {
  const root = mkTmpRoot('clodex-spill-');
  const proj = mkTmpRoot('clodex-spill-');
  const sha = repo ? mkRepo(proj, subject) : null;
  if (tickets.length) createTicketsStore({ clodexHome: root }).save(proj, tickets);
  const team = {
    name: 'team', root: proj, lead: 'lead',
    roles: { lead: { instantiate: 'session' }, hand: { instantiate: 'session' } },
  };
  const injected = [];
  const deps = {
    knownSkillNames: () => [],
    getRemoteServer: () => null,
    getUiSettings: () => ({ get: () => ({}) }),
    getPersistence: () => ({ list: () => [], get: () => null }),
    notifyOS: () => {},
    intentEnabled,
    withoutPrivilegedIntentsFor: require('../intent-registry').withoutPrivilegedIntentsFor,
    fencedLines: require('../intent-scanner').fencedLines,
    bodyModeFor: require('../intent-registry').bodyModeFor,
    intentEnabledFor: require('../intent-registry').intentEnabledFor,
    intentEnabledForSeat: require('../intent-registry').intentEnabledForSeat,
    pluginRowFor: require('../intent-registry').pluginRowFor,
    validIntentNames: require('../intent-registry').validIntentNames,
    fs,
    path,
    countPending: require('../pending-store').countPending,
    isDraftOpen: require('../proxy-util').isDraftOpen,
    drainPending: require('../pending-store').drainPending,
    hasActivePending: require('../pending-store').hasActivePending,
    peerStatusLabel: require('../proxy-util').peerStatusLabel,
    termAvailableFor: require('../drawer-avail').termAvailableFor,
    spillToFile: () => '/tmp/spill-stub.txt',
    MSG_MAX_AGE: 1800,
    REGISTRY_DIR: root,
    MSG_DIR: path.join(root, 'messages'),
    PENDING_DIR: path.join(root, 'pending'),
    pathFor,
    runDirFor,
    appVersion: '9.9.9',
    gitWorktree,
    ensureDir: (d) => fs.mkdirSync(d, { recursive: true }),
    resolveTeam: (cwd) => (withTeam && cwd === proj ? team : null),
    findProjectRoot: (cwd) => (cwd === proj ? proj : null),
    log: { info: () => {}, debug: () => {}, error: () => {}, warn: () => {} },
  };
  const SM = createSessionManager(deps);
  const m = new SM();
  m._injectText = (s, text) => injected.push(text);
  m._broadcast = () => {};
  m._maybeFlushInjectQueue = () => {};
  const seat = { name: 'team-hand', agentType: 'claude', type: 'claude', cwd: proj, workspaceId: 'ws1' };
  m.sessions.set(seat.name, seat);
  return { m, root, proj, sha, seat, injected, team };
}

function spilled(h, text = AUTHOR) {
  const line = h.m._handoffText(h.seat, text);
  const p = line.slice('Continue from your handoff: @'.length).trimEnd();
  return { line, path: p, body: fs.readFileSync(p, 'utf8') };
}

test('the spilled handoff file ends with the generated snapshot, the author text byte-identical above it', () => {
  const h = mkSnap({ tickets: [{ id: 't1', title: 'still going', role: 'hand', state: 'open', openedAt: Date.now() - 3600_000, closedAt: null }] });
  const out = spilled(h);

  const cut = out.body.indexOf(SEP);
  assert.ok(cut > 0, `the file carries the separator: ${out.body.slice(0, 200)}`);
  assert.strictEqual(out.body.slice(0, cut), AUTHOR,
    'the author\'s words are untouched — the snapshot is appended, never interleaved');
  const snap = out.body.slice(cut + SEP.length);
  assert.match(snap, /^State at resume \(generated by Clodex, \d{4}-\d{2}-\d{2}T[\d:.]+Z; not the author's words\):\n/,
    'and it says, in the first line of its own, that the bytes below are not the author\'s');
  assert.match(snap, new RegExp(`\\nhost 9\\.9\\.9; master ${h.sha} "the base commit" \\(${h.proj.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\)\\n`));
  assert.match(snap, /\nteam team, role hand: team-hand \(idle /);
  assert.match(snap, /\nt1 \[open\] hand .* — still going/, 'the open board rides along');
});

test('the injected line is byte-identical to the pre-snapshot one — only the FILE grew', () => {
  const h = mkSnap();
  const out = spilled(h);
  assert.strictEqual(out.line, `Continue from your handoff: @${out.path} `,
    'the trailing space that closes the CLI @-autocomplete popup is still the last byte');
  assert.notStrictEqual(path.basename(out.path), `${spillIdOf(AUTHOR)}.md`,
    'and the id is content-addressed over author+snapshot, so it is NOT the author-only id');
});

test('a seat on no team gets host and git only — no roster line, no board', () => {
  const h = mkSnap({ withTeam: false, tickets: [{ id: 't1', title: 'invisible', role: 'hand', state: 'open', openedAt: Date.now(), closedAt: null }] });
  const snap = spilled(h).body.split(SEP)[1];

  assert.match(snap, new RegExp(`^State at resume[^\\n]*\\nhost 9\\.9\\.9; master ${h.sha} "the base commit" \\(`));
  assert.strictEqual(snap.split('\n').length, 3, `two lines and the trailing newline, nothing else: ${JSON.stringify(snap)}`);
  assert.ok(!/team /.test(snap) && !/t1 /.test(snap), 'neither a roster nor a board is invented for a teamless seat');
});

test('a cwd that is no git repo → "git: unavailable", and the rest of the section still lands', () => {
  const h = mkSnap({ repo: false, tickets: [{ id: 't7', title: 'on the board', role: 'hand', state: 'open', openedAt: Date.now(), closedAt: null }] });
  const snap = spilled(h).body.split(SEP)[1];

  assert.match(snap, /\nhost 9\.9\.9; git: unavailable\n/,
    'named as unavailable rather than guessed at — a wrong sha is worse than none');
  assert.match(snap, /\nteam team, role hand: team-hand \(idle /, 'the roster is unaffected');
  assert.match(snap, /\nt7 \[open\] hand/, 'and so is the board');
});

test('a short body still takes the typed path: no spill, no snapshot', () => {
  const h = mkSnap();
  assert.ok(Buffer.byteLength(SHORT, 'utf8') <= SPILL_MIN_BYTES, 'ENTER: the fixture is under the spill floor');
  assert.strictEqual(h.m._handoffText(h.seat, SHORT), SHORT,
    'typed verbatim — a snapshot here would put generated bytes into the seat\'s prompt line');
  assert.ok(!fs.existsSync(path.join(h.root, 'spill')), 'and nothing was written');
});

test('a codex seat is still never spilled to, so it is never snapshotted either', () => {
  const h = mkSnap();
  h.seat.agentType = 'codex';
  assert.strictEqual(h.m._handoffText(h.seat, AUTHOR), AUTHOR);
  assert.ok(!fs.existsSync(path.join(h.root, 'spill')));
});

test('the cap truncates board rows last-first, names the count, and never sheds host/git/roster', () => {
  const head = 'State at resume (generated by Clodex, 2026-01-01T00:00:00.000Z; not the author\'s words):\n'
    + 'host 9.9.9; master abc1234 "the base commit" (/proj)\nteam team, role hand: team-hand (idle 1m)';
  const rows = Array.from({ length: 400 }, (_, i) => `t${i} [open] hand 1m ago — ${'r'.repeat(40)}`);
  const out = capResumeSnapshot(`---\n${head}`, rows.join('\n'));

  assert.ok(Buffer.byteLength(out, 'utf8') <= SNAPSHOT_MAX_BYTES, `capped: ${Buffer.byteLength(out, 'utf8')} bytes`);
  assert.ok(out.startsWith(`---\n${head}\n`), 'the head lines are whole — they are what the board cannot answer');
  const lines = out.split('\n');
  const marker = lines[lines.length - 1];
  const m = /^\(… (\d+) more rows — \[agent:task list\]\)$/.exec(marker);
  assert.ok(m, `the last line is the marker: ${marker}`);
  const kept = lines.filter((l) => /^t\d+ \[open\]/.test(l));
  assert.strictEqual(kept.length + Number(m[1]), 400, 'the count names exactly the rows that were dropped');
  assert.strictEqual(kept[0], rows[0], 'and the rows kept are the FIRST ones — the tail is what gave way');
});

test('a board under the cap is carried whole, with no marker line', () => {
  const rows = ['t1 [open] hand 1m ago — one', 't2 [open] hand 2m ago — two'];
  const out = capResumeSnapshot('---\nhead', rows.join('\n'));
  assert.strictEqual(out, `---\nhead\n${rows.join('\n')}`);
});

test('the compact continuation fires the same snapshotted file', async () => {
  const h = mkSnap();
  h.seat._compactContinuation = AUTHOR;
  h.m._fireCompactContinuation(h.seat);
  await new Promise((r) => setTimeout(r, 20));

  assert.strictEqual(h.injected.length, 1, 'one pointer line');
  const p = h.injected[0].slice('Continue from your handoff: @'.length).trimEnd();
  assert.ok(fs.readFileSync(p, 'utf8').includes(SEP), 'and the file it names carries the snapshot');
});

test('the reload handoff takes the same route', async () => {
  const h = mkSnap();
  const link = pathFor(h.root, 'team-hand', 'transcript');
  fs.mkdirSync(path.dirname(link), { recursive: true });
  fs.symlinkSync(path.join(h.root, 'conv.jsonl'), link);

  await h.m._injectReloadHandoff(h.seat, AUTHOR, 1000);

  assert.strictEqual(h.injected.length, 1);
  const p = h.injected[0].slice('Continue from your handoff: @'.length).trimEnd();
  assert.match(fs.readFileSync(p, 'utf8'), /State at resume \(generated by Clodex/);
});

test('an empty board still gets the roster and the store\'s own no-tickets wording', () => {
  const h = mkSnap();
  const snap = spilled(h).body.split(SEP)[1];
  assert.match(snap, /\nteam team, role hand: team-hand \(idle /);
  assert.match(snap, /\nno tickets on team\n?$/, 'the board block is the listing\'s own answer, not a second phrasing');
});

test('a board too big for the cap is truncated ON THE REAL PATH, host/git/roster intact', () => {
  const now = Date.now();
  const tickets = Array.from({ length: 200 }, (_, i) => ({
    id: `t${i + 1}`, title: `row ${i} ${'w'.repeat(40)}`, role: 'hand', state: 'open',
    openedAt: now - 3600_000, closedAt: null,
  }));
  const h = mkSnap({ tickets });
  const snap = spilled(h).body.split(SEP)[1];

  assert.ok(Buffer.byteLength(`---\n${snap}`, 'utf8') <= SNAPSHOT_MAX_BYTES + 1,
    `the generated section is capped: ${Buffer.byteLength(snap, 'utf8')} bytes`);
  assert.match(snap, new RegExp(`\\nhost 9\\.9\\.9; master ${h.sha} "the base commit" \\(`));
  assert.match(snap, /\nteam team, role hand: team-hand \(idle /);
  const m = /\n\(… (\d+) more rows — \[agent:task list\]\)\n?$/.exec(snap);
  assert.ok(m, `the marker is the section's last line: ${JSON.stringify(snap.slice(-120))}`);
  const kept = snap.split('\n').filter((l) => /^t\d+ \[open\]/.test(l)).length;
  assert.ok(kept > 0 && kept < 200, `some rows survived and some did not: kept ${kept}`);
  assert.strictEqual(kept + Number(m[1]), 200, 'the count names exactly the ticket rows that were dropped');
  assert.match(snap, /\ntickets on team:\n/, 'and the listing head line is not one of the rows that gave way');
});
