'use strict';
// Unit tests for sandbox.js (sandbox-plan.md [internal design doc, not in this repo] M1) — the pure parts (compose
// bytes, port bump, image resolution, ps parsing) plus the factory's spawn/
// docker-mocked behavior (detection, idempotent peer registration, up/down).

const test = require('node:test');
const assert = require('node:assert');
const { EventEmitter } = require('node:events');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

// A throwaway userData dir for the tests that let writeComposeFile actually
// write; removed on process exit.
const TMP_USERDATA = fs.mkdtempSync(path.join(os.tmpdir(), 'clx-sandbox-'));
const TMP_REGISTRY = fs.mkdtempSync(path.join(os.tmpdir(), 'clx-registry-'));
process.on('exit', () => { try { fs.rmSync(TMP_USERDATA, { recursive: true, force: true }); } catch {} });
process.on('exit', () => { try { fs.rmSync(TMP_REGISTRY, { recursive: true, force: true }); } catch {} });

const {
  createSandbox, createSandboxManager,
  createDetectCache, dockerUnavailableError,
  resolveImage, resolvePorts, nextFreePort, generateCompose,
  parseOwnPorts, parseOwnPortMap, parsePsRows, parseComposeState,
  normalizeMounts, translatePath, composeProjectName,
  DEFAULT_CONFIG, CONTAINER_PORTS, SANDBOX_PEER_ID,
} = require('../sandbox');

// Compose calls are now `['compose','-p',<project>,'-f',<path>, <sub…>]` — the
// subcommand starts right after the `-f <path>` pair. This slices it out for the
// arg-vector assertions (rebuild's up/pull/build choices).
function composeSubcommands(calls) {
  return calls
    .filter((a) => a.includes('compose'))
    .map((a) => a.slice(a.indexOf('-f') + 2));
}

// ── resolveImage ────────────────────────────────────────────────────────────

test('resolveImage: packaged app pins the GHCR version tag', () => {
  const r = resolveImage({ isPackaged: true, appVersion: '2.24.0', override: null, repoRoot: '/repo' });
  assert.deepStrictEqual(r, { kind: 'image', image: 'ghcr.io/avirtual/clodex:2.24.0' });
});

test('resolveImage: dev build:s from the repo checkout (no GHCR)', () => {
  const r = resolveImage({ isPackaged: false, appVersion: '2.24.0', override: null, repoRoot: '/repo' });
  assert.deepStrictEqual(r, { kind: 'build', context: '/repo', dockerfile: 'docker/web/Dockerfile' });
});

test('resolveImage: an explicit override wins in any state', () => {
  const packaged = resolveImage({ isPackaged: true, appVersion: '2.24.0', override: 'my/img:tag', repoRoot: '/repo' });
  const dev = resolveImage({ isPackaged: false, appVersion: '2.24.0', override: 'my/img:tag', repoRoot: '/repo' });
  assert.deepStrictEqual(packaged, { kind: 'image', image: 'my/img:tag' });
  assert.deepStrictEqual(dev, { kind: 'image', image: 'my/img:tag' });
});

// ── port bump ───────────────────────────────────────────────────────────────

test('nextFreePort: returns the desired port when free', () => {
  assert.strictEqual(nextFreePort(7810, () => false, new Set()), 7810);
});

test('nextFreePort: bumps past a listener', () => {
  const busy = new Set([7810, 7811]);
  assert.strictEqual(nextFreePort(7810, (p) => busy.has(p), new Set()), 7812);
});

test('nextFreePort: skips ports already claimed in this generation', () => {
  const taken = new Set([7810]);
  assert.strictEqual(nextFreePort(7810, () => false, taken), 7811);
  assert.ok(taken.has(7811));
});

test('resolvePorts: all three free → the configured defaults', () => {
  const ports = resolvePorts(DEFAULT_CONFIG, () => false);
  assert.deepStrictEqual(ports, { web: 7810, wirescope: 7811, wire: 7820 });
});

test('resolvePorts: collisions bump each port, no two collapse onto one', () => {
  // 7810 (web default) and 7820 (wire default) are held; web bumps to 7811, but
  // wirescope's default IS 7811, so it must bump again — and never onto web's.
  const busy = new Set([7810, 7820]);
  const ports = resolvePorts(DEFAULT_CONFIG, (p) => busy.has(p));
  assert.strictEqual(ports.web, 7811);
  assert.strictEqual(ports.wirescope, 7812); // 7811 taken by web this generation
  assert.strictEqual(ports.wire, 7821);
  // Distinctness invariant.
  assert.strictEqual(new Set([ports.web, ports.wirescope, ports.wire]).size, 3);
});

// ── generateCompose ─────────────────────────────────────────────────────────

const DEV_IMAGE = { kind: 'build', context: '/repo', dockerfile: 'docker/web/Dockerfile' };
const PORTS = { web: 7810, wirescope: 7811, wire: 7820 };
const STATE_DIR = '/h/.clodex/boxes/x';

test('generateCompose: dev build variant with a named work volume', () => {
  const yaml = generateCompose({ image: DEV_IMAGE, ports: PORTS, stateDir: STATE_DIR, workDir: null, authEnvFile: null });
  assert.match(yaml, /^# GENERATED by Clodex/m);
  assert.match(yaml, /hostname: sandbox/);
  assert.match(yaml, /build:\n {6}context: \/repo\n {6}dockerfile: docker\/web\/Dockerfile/);
  // Three loopback publishes host<config> → container<fixed>.
  assert.match(yaml, /- "127\.0\.0\.1:7810:8080"/);
  assert.match(yaml, /- "127\.0\.0\.1:7811:7800"/);
  assert.match(yaml, /- "127\.0\.0\.1:7820:7900"/);
  // Named work volume + its declaration.
  assert.match(yaml, /- clodex-work:\/home\/clodex\/work/);
  assert.match(yaml, /^ {2}clodex-work:$/m);
  // Wirescope public URL tracks the host port.
  assert.match(yaml, /CLODEX_WIRESCOPE_PUBLIC_URL: "\$\{CLODEX_WIRESCOPE_PUBLIC_URL:-http:\/\/localhost:7811\}"/);
  // Compose interpolations survive untouched (not eaten by JS).
  assert.match(yaml, /CLODEX_WEB_TOKEN: "\$\{CLODEX_WEB_TOKEN:-\}"/);
  // Fixed lifecycle bits mirrored from docker/web/compose.yaml.
  assert.match(yaml, /init: true/);
  assert.match(yaml, /restart: always/);
  assert.match(yaml, /healthcheck:/);
  // No image: line in the dev/build variant, no env_file without an auth file.
  assert.doesNotMatch(yaml, /^ {4}image:/m);
  assert.doesNotMatch(yaml, /env_file:/);
});

test('generateCompose: packaged image variant with a host bind-mount', () => {
  const image = { kind: 'image', image: 'ghcr.io/avirtual/clodex:2.24.0' };
  const yaml = generateCompose({ image, ports: PORTS, stateDir: STATE_DIR, workDir: '/Users/me/work', authEnvFile: null });
  assert.match(yaml, /^ {4}image: ghcr\.io\/avirtual\/clodex:2\.24\.0$/m);
  assert.doesNotMatch(yaml, /build:/);
  // Bind mount (double-quoted), and NO clodex-work named volume declared.
  assert.match(yaml, /- "\/Users\/me\/work:\/home\/clodex\/work"/);
  assert.doesNotMatch(yaml, /- clodex-work:\/home\/clodex\/work/);
  assert.doesNotMatch(yaml, /^ {2}clodex-work:$/m);
});

test('generateCompose: bumped ports flow into every publish + the public URL', () => {
  const yaml = generateCompose({
    image: DEV_IMAGE, ports: { web: 7811, wirescope: 7812, wire: 7821 }, stateDir: STATE_DIR, workDir: null, authEnvFile: null,
  });
  assert.match(yaml, /- "127\.0\.0\.1:7811:8080"/);
  assert.match(yaml, /- "127\.0\.0\.1:7812:7800"/);
  assert.match(yaml, /- "127\.0\.0\.1:7821:7900"/);
  assert.match(yaml, /CLODEX_WIRESCOPE_PUBLIC_URL:.*localhost:7812/);
});

test('generateCompose: auth env_file referenced by path, never inlined (M4 hook)', () => {
  const yaml = generateCompose({
    image: DEV_IMAGE, ports: PORTS, stateDir: STATE_DIR, workDir: null, authEnvFile: '/data/sandbox/auth.env',
  });
  // Quoted like the workDir bind — userData paths carry spaces on macOS.
  assert.match(yaml, /env_file:\n {6}- "\/data\/sandbox\/auth\.env"/);
  // A hook point only — no secret material lands in the bytes.
  assert.doesNotMatch(yaml, /CLAUDE_CODE_OAUTH_TOKEN/);
});

test('generateCompose: healthcheck probes the fixed container web port', () => {
  const yaml = generateCompose({ image: DEV_IMAGE, ports: PORTS, stateDir: STATE_DIR, workDir: null, authEnvFile: null });
  assert.ok(yaml.includes(`http://127.0.0.1:${CONTAINER_PORTS.web}/healthz`));
});

test('generateCompose: a workDir with spaces is double-quoted so YAML keeps it verbatim', () => {
  const yaml = generateCompose({
    image: DEV_IMAGE, ports: PORTS, stateDir: STATE_DIR, workDir: '/Users/me/My Work #1', authEnvFile: null,
  });
  assert.match(yaml, /- "\/Users\/me\/My Work #1:\/home\/clodex\/work"/);
});

test('generateCompose: read-only host library binds layered on clodex-dot (M5 Decision 7)', () => {
  const yaml = generateCompose({
    image: DEV_IMAGE, ports: PORTS, stateDir: STATE_DIR, workDir: null, authEnvFile: null, libDir: '/Users/me/.clodex',
  });
  // Three ro binds: skills, agents, and one `library` dir (covers prompts+exec).
  assert.match(yaml, /- "\/Users\/me\/\.clodex\/skills:\/home\/clodex\/\.clodex\/skills:ro"/);
  assert.match(yaml, /- "\/Users\/me\/\.clodex\/agents:\/home\/clodex\/\.clodex\/agents:ro"/);
  assert.match(yaml, /- "\/Users\/me\/\.clodex\/library:\/home\/clodex\/\.clodex\/library:ro"/);
  assert.match(yaml, /- "\/h\/\.clodex\/boxes\/x\/dot:\/home\/clodex\/\.clodex"\n( +- "[^\n]*:ro"\n){3} +- "\/h\/\.clodex\/boxes\/x\/claude:\/home\/clodex\/\.claude"/);
  // One `library` bind covers prompts + exec — no separate exec mount.
  assert.doesNotMatch(yaml, /\/exec:ro/);
  assert.ok(yaml.includes('- "/h/.clodex/boxes/x/data:/data"'));
  assert.doesNotMatch(yaml, /^ {2}(clodex-data|clodex-dot|claude-auth):$/m);
  assert.match(yaml, /^ {2}clodex-work:$/m);
});

test('generateCompose: a missing or relative stateDir throws (no box on a guessed path)', () => {
  const base = { image: DEV_IMAGE, ports: PORTS, workDir: null, authEnvFile: null };
  assert.throws(() => generateCompose({ ...base }), /stateDir must be an absolute path/);
  assert.throws(() => generateCompose({ ...base, stateDir: 'boxes/x' }), /stateDir must be an absolute path/);
});

test('generateCompose: blast radius — no bind exposes $HOME, ~/.clodex or an ancestor of the project', () => {
  const yaml = generateCompose({
    image: DEV_IMAGE, ports: PORTS, workDir: '/h/proj/app', authEnvFile: null,
    stateDir: '/h/.clodex/boxes/x', libDir: '/h/lib', mounts: [{ host: '/h/proj/app/notes' }],
  });
  const lines = yaml.split('\n');
  const hosts = [];
  for (let i = lines.indexOf('    volumes:') + 1; i < lines.length && lines[i].startsWith('      '); i++) {
    const entry = lines[i].replace(/^ +- /, '').replace(/^"|"$/g, '');
    hosts.push(entry.split(':')[0]);
  }
  assert.ok(hosts.length >= 6, `expected every bind host, collected ${hosts.length}`);
  for (const p of hosts) {
    assert.notStrictEqual(p, '/h', 'a bind exposed the whole home');
    assert.notStrictEqual(p, '/h/.clodex', 'a bind exposed the desktop clodex home');
    assert.strictEqual('/h/proj/app'.startsWith(`${p}/`), false, `${p} is an ancestor of the project dir`);
  }
});

test('generateCompose: no library binds when libDir is absent (guard for none-passing callers)', () => {
  const yaml = generateCompose({ image: DEV_IMAGE, ports: PORTS, stateDir: STATE_DIR, workDir: null, authEnvFile: null });
  assert.doesNotMatch(yaml, /:ro"/);
  assert.doesNotMatch(yaml, /home\/clodex\/\.clodex\/skills/);
});

test('generateCompose: hostname defaults to `sandbox`, overridable per box (M6b P1)', () => {
  // Omitted → the shared box id, keeping the single-box bytes byte-stable.
  const shared = generateCompose({ image: DEV_IMAGE, ports: PORTS, stateDir: STATE_DIR, workDir: null, authEnvFile: null });
  assert.match(shared, /^ {4}hostname: sandbox$/m);
  // A per-box hostname (= its wire SELF_LABEL) is swapped in so two boxes don't
  // both self-identify as 'sandbox'.
  const named = generateCompose({ image: DEV_IMAGE, ports: PORTS, stateDir: STATE_DIR, workDir: null, authEnvFile: null, hostname: 'proj-x' });
  assert.match(named, /^ {4}hostname: proj-x$/m);
  assert.doesNotMatch(named, /hostname: sandbox/);
});

// ── generateCompose: user mounts (M6a) ──────────────────────────────────────

test('generateCompose: a single mount with a derived target, read-write by default', () => {
  const yaml = generateCompose({
    image: DEV_IMAGE, ports: PORTS, stateDir: STATE_DIR, workDir: null, authEnvFile: null,
    mounts: [{ host: '/Users/me/projects/foo' }],
  });
  // Derived target = /home/clodex/<basename>, no :ro suffix (RW default).
  assert.match(yaml, /- "\/Users\/me\/projects\/foo:\/home\/clodex\/foo"/);
  assert.doesNotMatch(yaml, /\/home\/clodex\/foo:ro/);
});

test('generateCompose: multiple mounts, ro flag emits :ro, explicit target honored', () => {
  const yaml = generateCompose({
    image: DEV_IMAGE, ports: PORTS, stateDir: STATE_DIR, workDir: null, authEnvFile: null,
    mounts: [
      { host: '/Users/me/code/app', ro: false },
      { host: '/Users/me/reference/docs', ro: true },
      { host: '/data-host/blob', container: '/home/clodex/blob' },
    ],
  });
  assert.match(yaml, /- "\/Users\/me\/code\/app:\/home\/clodex\/app"/);
  assert.match(yaml, /- "\/Users\/me\/reference\/docs:\/home\/clodex\/docs:ro"/);
  assert.match(yaml, /- "\/data-host\/blob:\/home\/clodex\/blob"/);
});

test('generateCompose: two hosts sharing a basename get deterministic -N targets', () => {
  const yaml = generateCompose({
    image: DEV_IMAGE, ports: PORTS, stateDir: STATE_DIR, workDir: null, authEnvFile: null,
    mounts: [{ host: '/a/shared' }, { host: '/b/shared' }, { host: '/c/shared' }],
  });
  assert.match(yaml, /- "\/a\/shared:\/home\/clodex\/shared"/);
  assert.match(yaml, /- "\/b\/shared:\/home\/clodex\/shared-2"/);
  assert.match(yaml, /- "\/c\/shared:\/home\/clodex\/shared-3"/);
});

test('generateCompose: a mount source with spaces/# is double-quoted verbatim', () => {
  const yaml = generateCompose({
    image: DEV_IMAGE, ports: PORTS, stateDir: STATE_DIR, workDir: null, authEnvFile: null,
    mounts: [{ host: '/Users/me/My Notes #2', container: '/home/clodex/notes' }],
  });
  assert.match(yaml, /- "\/Users\/me\/My Notes #2:\/home\/clodex\/notes"/);
});

// The test above is right about the characters its author tried. These are the
// characters the QUOTING STYLE ITSELF makes special, which is the class a
// "double-quoted, so it survives verbatim" claim cannot cover by construction:
// a bare `"` closes the scalar early, a bare `\` opens an escape sequence (`\b`
// silently becomes a backspace), and a raw newline ends the list item. Pinned as
// exact bytes because the shipped defect looked quoted.
test('generateCompose: a mount source containing `"`, `\\` or a newline stays one valid entry', () => {
  const cases = [
    ['/tmp/a"b', '      - "/tmp/a\\"b:/home/clodex/x"'],
    ['/tmp/a\\b', '      - "/tmp/a\\\\b:/home/clodex/x"'],
    ['/tmp/a\nb', '      - "/tmp/a\\nb:/home/clodex/x"'],
    ['/tmp/a\tb', '      - "/tmp/a\\tb:/home/clodex/x"'],
  ];
  for (const [host, expected] of cases) {
    const yaml = generateCompose({
      image: DEV_IMAGE, ports: PORTS, stateDir: STATE_DIR, workDir: null, authEnvFile: null,
      mounts: [{ host, container: '/home/clodex/x' }],
    });
    assert.ok(yaml.split('\n').includes(expected),
      `${JSON.stringify(host)} → expected the line ${JSON.stringify(expected)}`);
  }
});

// Every path interpolated into the document goes through the same quoting, so
// the assertion is made once over all four sites at once: a newline in ANY of
// them must not add a line, because a split entry is parsed as its own list
// item (or as a stray scalar under `volumes:`).
test('generateCompose: a newline in any interpolated path cannot split the document', () => {
  const args = { image: DEV_IMAGE, ports: PORTS, stateDir: STATE_DIR };
  const hostile = generateCompose({
    ...args,
    workDir: '/tmp/work"dir\nA', authEnvFile: '/tmp/auth"env\nB',
    libDir: '/tmp/lib"dir\nC', mounts: [{ host: '/tmp/m"nt\nD', container: '/home/clodex/x' }],
  });
  const plain = generateCompose({
    ...args,
    workDir: '/tmp/workdir', authEnvFile: '/tmp/authenv',
    libDir: '/tmp/libdir', mounts: [{ host: '/tmp/mnt', container: '/home/clodex/x' }],
  });
  assert.strictEqual(hostile.split('\n').length, plain.split('\n').length,
    'a path containing a newline added lines to the compose document');

  // …and the volumes block in particular holds only list items, never a
  // fragment left behind by a broken entry.
  const lines = hostile.split('\n');
  const block = [];
  for (let i = lines.indexOf('    volumes:') + 1; i < lines.length && lines[i].startsWith('      '); i++) {
    block.push(lines[i]);
  }
  assert.ok(block.length >= 5, `the volumes block did not form: ${block.length} lines`);
  for (const l of block) assert.match(l, /^ {6}- /, `orphan line under volumes: ${JSON.stringify(l)}`);
});

test('generateCompose: a mount shadowing a reserved path THROWS (no broken box)', () => {
  for (const target of ['/home/clodex/work', '/home/clodex/.clodex', '/home/clodex/.clodex/run', '/home/clodex', '/data', '/home/clodex/.claude']) {
    assert.throws(() => generateCompose({
      image: DEV_IMAGE, ports: PORTS, stateDir: STATE_DIR, workDir: null, authEnvFile: null,
      mounts: [{ host: '/Users/me/x', container: target }],
    }), /would shadow/, `target ${target} must be refused`);
  }
});

test('generateCompose: no mount binds when the list is empty or absent', () => {
  const empty = generateCompose({ image: DEV_IMAGE, ports: PORTS, stateDir: STATE_DIR, workDir: null, authEnvFile: null, mounts: [] });
  const absent = generateCompose({ image: DEV_IMAGE, ports: PORTS, stateDir: STATE_DIR, workDir: null, authEnvFile: null });
  assert.doesNotMatch(empty, /\/home\/clodex\/(?!work|\.clodex|\.claude)/);
  assert.strictEqual(empty, absent);   // omitting mounts === passing []
});

// ── normalizeMounts (pure, M6a) ─────────────────────────────────────────────

test('normalizeMounts: derives targets, defaults RW, keeps explicit + ro', () => {
  const r = normalizeMounts([
    { host: '/a/foo' },
    { host: '/b/bar', ro: true },
    { host: '/c/baz', container: '/home/clodex/custom' },
  ]);
  assert.deepStrictEqual(r.mounts, [
    { host: '/a/foo', container: '/home/clodex/foo', ro: false },
    { host: '/b/bar', container: '/home/clodex/bar', ro: true },
    { host: '/c/baz', container: '/home/clodex/custom', ro: false },
  ]);
});

test('normalizeMounts: skips blank rows, rejects relative host or target', () => {
  assert.deepStrictEqual(normalizeMounts([{ host: '  ' }, { host: '' }, {}]).mounts, []);
  assert.match(normalizeMounts([{ host: 'relative/path' }]).error, /absolute/);
  assert.match(normalizeMounts([{ host: '/ok', container: 'rel/target' }]).error, /absolute/);
});

test('normalizeMounts: rejects an explicit duplicate target, suffixes derived ones', () => {
  assert.match(normalizeMounts([
    { host: '/a/x', container: '/home/clodex/dup' },
    { host: '/b/y', container: '/home/clodex/dup' },
  ]).error, /Duplicate/);
  // Derived collisions do NOT error — they suffix.
  const ok = normalizeMounts([{ host: '/a/dup' }, { host: '/b/dup' }]);
  assert.deepStrictEqual(ok.mounts.map((m) => m.container), ['/home/clodex/dup', '/home/clodex/dup-2']);
});

test('normalizeMounts: reserved-path shadow is refused in both nesting directions', () => {
  // Target nested under a reserved path.
  assert.match(normalizeMounts([{ host: '/h', container: '/home/clodex/.clodex/run' }]).error, /shadow/);
  // Target that is an ancestor of reserved paths.
  assert.match(normalizeMounts([{ host: '/h', container: '/home/clodex' }]).error, /shadow/);
  // Exact reserved path.
  assert.match(normalizeMounts([{ host: '/h', container: '/data' }]).error, /shadow/);
});

// The enumerations elsewhere in this file can only ever check MEMBERS of
// RESERVED_MOUNT_TARGETS and paths that visibly nest under one. What they
// structurally exclude is the class of targets that DOMINATE the whole set — a
// target does not have to resemble any reserved path to shadow all four, and
// `/` is that class's extreme. It was the one value the guard admitted, because
// the old prefix test built `'//'` and nothing starts with that. A seventh
// entry in the enumeration could never have caught this; the defect lives in
// what the enumeration leaves out, not in what it lists.
test('normalizeMounts: a target that DOMINATES the reserved set is refused, root included', () => {
  for (const target of ['/', '/home', '/home/clodex']) {
    const r = normalizeMounts([{ host: '/h', container: target }]);
    assert.match(r.error || '', /shadow/, `target ${target} must be refused`);
  }
  // A trailing slash names the same target and must not be a way around it.
  assert.match(normalizeMounts([{ host: '/h', container: '/data/' }]).error || '', /shadow/);
  // The control that stops "refuse everything" from passing this test: a shared
  // string prefix is not containment, so /homework does not shadow /home/*.
  assert.deepStrictEqual(
    normalizeMounts([{ host: '/h', container: '/homework' }]).mounts,
    [{ host: '/h', container: '/homework', ro: false }],
  );
});

// ── translatePath: host folder → container path (M6a New Session picker) ─────

test('translatePath: a folder under the work dir maps to /home/clodex/work[/rel]', () => {
  // Exact workDir → the mount point itself.
  assert.deepStrictEqual(
    translatePath({ hostPath: '/Users/me/work', workDir: '/Users/me/work', mounts: [] }),
    { container: '/home/clodex/work' });
  // A nested subpath → work + the relative remainder.
  assert.deepStrictEqual(
    translatePath({ hostPath: '/Users/me/work/proj/src', workDir: '/Users/me/work', mounts: [] }),
    { container: '/home/clodex/work/proj/src' });
});

test('translatePath: a folder under a derived-target mount maps to that target + rel', () => {
  const mounts = [{ host: '/Users/me/code/app' }];   // derived → /home/clodex/app
  assert.deepStrictEqual(
    translatePath({ hostPath: '/Users/me/code/app', workDir: null, mounts }),
    { container: '/home/clodex/app' });
  assert.deepStrictEqual(
    translatePath({ hostPath: '/Users/me/code/app/lib/x', workDir: null, mounts }),
    { container: '/home/clodex/app/lib/x' });
});

test('translatePath: an explicit-target mount is honored', () => {
  const mounts = [{ host: '/data/blob', container: '/home/clodex/blob' }];
  assert.deepStrictEqual(
    translatePath({ hostPath: '/data/blob/sub', workDir: null, mounts }),
    { container: '/home/clodex/blob/sub' });
});

test('translatePath: derived-target -N collision remainder tracks normalizeMounts', () => {
  const mounts = [{ host: '/a/shared' }, { host: '/b/shared' }];   // → shared, shared-2
  assert.deepStrictEqual(
    translatePath({ hostPath: '/b/shared/deep', workDir: null, mounts }),
    { container: '/home/clodex/shared-2/deep' });
});

test('translatePath: the most specific (longest) host prefix wins', () => {
  // A mount nested UNDER the work dir maps to the mount, not to work.
  const mounts = [{ host: '/Users/me/work/special', container: '/home/clodex/special' }];
  assert.deepStrictEqual(
    translatePath({ hostPath: '/Users/me/work/special/x', workDir: '/Users/me/work', mounts }),
    { container: '/home/clodex/special/x' });
});

test('translatePath: an unreachable folder returns { reachable:false }', () => {
  assert.deepStrictEqual(
    translatePath({ hostPath: '/Users/me/elsewhere', workDir: '/Users/me/work', mounts: [] }),
    { reachable: false });
  // A sibling that merely shares a prefix string is NOT under the dir (boundary-safe).
  assert.deepStrictEqual(
    translatePath({ hostPath: '/Users/me/workshop', workDir: '/Users/me/work', mounts: [] }),
    { reachable: false });
  // No workDir and no mounts → nothing is reachable.
  assert.deepStrictEqual(
    translatePath({ hostPath: '/anything', workDir: null, mounts: [] }),
    { reachable: false });
});

test('translatePath: a blank or relative host path is unreachable (never translated)', () => {
  assert.deepStrictEqual(translatePath({ hostPath: '', workDir: '/w', mounts: [] }), { reachable: false });
  assert.deepStrictEqual(translatePath({ hostPath: 'rel/path', workDir: '/w', mounts: [] }), { reachable: false });
});

test('translateHostPath: reads the live config (workDir + mounts) via getConfig', () => {
  const ud = freshUserData();
  const settings = fakeSettings();
  const dir = fs.mkdtempSync(path.join(TMP_USERDATA, 'mnt-'));
  const sb = createSandbox({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, getUserDataPath: () => ud });
  sb.setConfig({ workDir: '/Users/me/work' });
  assert.deepStrictEqual(sb.translateHostPath('/Users/me/work/a'), { container: '/home/clodex/work/a' });
  // Add a mount, and a path under it now translates against the derived target.
  sb.setConfig({ mounts: [{ host: dir }] });
  assert.deepStrictEqual(sb.translateHostPath(path.join(dir, 'sub')),
    { container: `/home/clodex/${path.basename(dir)}/sub` });
  assert.deepStrictEqual(sb.translateHostPath('/nowhere'), { reachable: false });
});

// ── setConfig mount validation on save (M6a) ────────────────────────────────

test('setConfig: persists valid mounts (cleaned shape), derived target stays dynamic', () => {
  const ud = freshUserData();
  const settings = fakeSettings();
  const dir = fs.mkdtempSync(path.join(TMP_USERDATA, 'mnt-'));
  const sb = createSandbox({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, getUserDataPath: () => ud });
  const r = sb.setConfig({ mounts: [{ host: dir, ro: true }, { host: '  ' }] });
  assert.ok(!r.error, 'valid mounts accepted');
  // Blank row dropped; stored shape is { host, ro } with no derived container.
  assert.deepStrictEqual(settings._state().sandbox.mounts, [{ host: dir, ro: true }]);
  assert.deepStrictEqual(sb.getConfig().mounts, [{ host: dir, ro: true }]);
});

test('setConfig: rejects a non-existent mount source, persists nothing', () => {
  const ud = freshUserData();
  const settings = fakeSettings();
  const sb = createSandbox({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, getUserDataPath: () => ud });
  const r = sb.setConfig({ mounts: [{ host: '/no/such/folder/xyzzy' }] });
  assert.strictEqual(r.ok, false);
  assert.match(r.error, /does not exist/);
  assert.strictEqual(settings._state().sandbox, undefined);   // nothing written
});

test('setConfig: rejects a mount whose source is a file, not a folder', () => {
  const ud = freshUserData();
  const settings = fakeSettings();
  const filePath = path.join(fs.mkdtempSync(path.join(TMP_USERDATA, 'f-')), 'a.txt');
  fs.writeFileSync(filePath, 'x');
  const sb = createSandbox({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, getUserDataPath: () => ud });
  const r = sb.setConfig({ mounts: [{ host: filePath }] });
  assert.strictEqual(r.ok, false);
  assert.match(r.error, /not a folder/);
});

test('setConfig: a shadow-target mount is refused at save, not just at generate', () => {
  const ud = freshUserData();
  const settings = fakeSettings();
  const dir = fs.mkdtempSync(path.join(TMP_USERDATA, 'mnt-'));
  const sb = createSandbox({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, getUserDataPath: () => ud });
  const r = sb.setConfig({ mounts: [{ host: dir, container: '/home/clodex/work' }] });
  assert.strictEqual(r.ok, false);
  assert.match(r.error, /shadow/);
});

test('setConfig: a non-mount write is untouched by mount validation', () => {
  const ud = freshUserData();
  const settings = fakeSettings();
  const sb = createSandbox({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, getUserDataPath: () => ud });
  const r = sb.setConfig({ webPort: 7999 });
  assert.ok(!r.error);
  assert.strictEqual(settings._state().sandbox.webPort, 7999);
});

// ── parseOwnPorts (self-collision guard) ────────────────────────────────────

test('parseOwnPorts: extracts the three published host ports from a compose file', () => {
  const yaml = generateCompose({
    image: DEV_IMAGE, ports: { web: 7811, wirescope: 7812, wire: 7821 }, stateDir: STATE_DIR, workDir: null, authEnvFile: null,
  });
  assert.deepStrictEqual(parseOwnPorts(yaml).sort((a, b) => a - b), [7811, 7812, 7821]);
});

test('parseOwnPorts: empty for missing/garbage input', () => {
  assert.deepStrictEqual(parseOwnPorts(''), []);
  assert.deepStrictEqual(parseOwnPorts(null), []);
  assert.deepStrictEqual(parseOwnPorts('services:\n  clodex:\n    image: x'), []);
});

test('parseOwnPortMap: maps published host ports back to roles by container port', () => {
  // Bumped ports (box 2 off box 1) — the role mapping is by the fixed CONTAINER
  // port each targets, so it survives the bump AND is order-independent.
  const yaml = generateCompose({
    image: DEV_IMAGE, ports: { web: 7812, wirescope: 7813, wire: 7821 }, stateDir: STATE_DIR, workDir: null, authEnvFile: null,
  });
  assert.deepStrictEqual(parseOwnPortMap(yaml), { web: 7812, wirescope: 7813, wire: 7821 });
});

test('parseOwnPortMap: empty for missing/garbage input', () => {
  assert.deepStrictEqual(parseOwnPortMap(''), {});
  assert.deepStrictEqual(parseOwnPortMap(null), {});
  assert.deepStrictEqual(parseOwnPortMap('services:\n  clodex:\n    image: x'), {});
});

// ── compose ps parsing ──────────────────────────────────────────────────────

test('parsePsRows: reads a JSON array', () => {
  const rows = parsePsRows('[{"Service":"clodex","State":"running"}]');
  assert.strictEqual(rows.length, 1);
  assert.strictEqual(rows[0].Service, 'clodex');
});

test('parsePsRows: reads newline-delimited JSON objects, skipping garbage', () => {
  const rows = parsePsRows('{"Service":"clodex","State":"exited"}\nnot json\n{"Service":"x","State":"running"}');
  assert.strictEqual(rows.length, 2);
  assert.strictEqual(rows[0].State, 'exited');
});

test('parseComposeState: running / exited / absent', () => {
  assert.strictEqual(parseComposeState('[{"Service":"clodex","State":"running"}]'), 'running');
  assert.strictEqual(parseComposeState('[{"Service":"clodex","State":"exited"}]'), 'exited');
  assert.strictEqual(parseComposeState(''), 'absent');
  assert.strictEqual(parseComposeState('[]'), 'absent');
  // Falls back to Status text when State is absent.
  assert.strictEqual(parseComposeState('[{"Service":"clodex","Status":"Up 3 minutes"}]'), 'running');
});

// ── factory: detection (spawn mocked) ───────────────────────────────────────

// A fake child process: emits 'error' or 'exit' on the next tick.
function fakeSpawn(behavior) {
  return () => {
    const child = new EventEmitter();
    child.stdout = new EventEmitter();
    child.stderr = new EventEmitter();
    child.kill = () => {};
    process.nextTick(() => {
      if (behavior.error) child.emit('error', behavior.error);
      else {
        if (behavior.stdout) child.stdout.emit('data', behavior.stdout);
        if (behavior.stderr) child.stderr.emit('data', behavior.stderr);
        child.emit('exit', behavior.code ?? 0);
      }
    });
    return child;
  };
}

test('detect: docker missing (ENOENT) → not present', async () => {
  const sb = createSandbox({ registryDir: TMP_REGISTRY, spawn: fakeSpawn({ error: Object.assign(new Error('nope'), { code: 'ENOENT' }) }) });
  assert.deepStrictEqual(await sb.detect(), { present: false, running: false });
});

test('detect: daemon down (non-zero exit) → present but not running', async () => {
  const sb = createSandbox({ registryDir: TMP_REGISTRY, spawn: fakeSpawn({ code: 1 }) });
  assert.deepStrictEqual(await sb.detect(), { present: true, running: false });
});

test('detect: healthy (exit 0) → present and running', async () => {
  const sb = createSandbox({ registryDir: TMP_REGISTRY, spawn: fakeSpawn({ code: 0 }) });
  assert.deepStrictEqual(await sb.detect(), { present: true, running: true });
});

// ── detect cache: TTL + in-flight dedupe (fake clock / injected probe) ──────

test('createDetectCache: caches within the TTL, re-probes past it', async () => {
  let clock = 1000;
  let probes = 0;
  const cache = createDetectCache({
    now: () => clock,
    ttlMs: 30000,
    probe: async () => { probes++; return { present: true, running: probes === 1 }; },
  });
  const a = await cache.get();
  assert.strictEqual(a.running, true);
  assert.strictEqual(a.cachedAt, 1000, 'result is stamped with the probe time');
  assert.strictEqual(probes, 1);

  clock += 29999;                     // still inside the TTL → cached, no new probe
  const b = await cache.get();
  assert.strictEqual(b.running, true);
  assert.strictEqual(b.cachedAt, 1000);
  assert.strictEqual(probes, 1);

  clock += 2;                         // now past the TTL → re-probe (running flips)
  const c = await cache.get();
  assert.strictEqual(c.running, false);
  assert.strictEqual(probes, 2);
});

test('createDetectCache: concurrent callers fold onto ONE in-flight probe', async () => {
  let probes = 0;
  let release;
  const gate = new Promise((res) => { release = res; });
  const cache = createDetectCache({
    now: () => 0,
    probe: async () => { probes++; await gate; return { present: true, running: true }; },
  });
  const p1 = cache.get();
  const p2 = cache.get();            // arrives while the first probe is still pending
  release();
  const [r1, r2] = await Promise.all([p1, p2]);
  assert.strictEqual(probes, 1, 'the two callers shared a single probe');
  assert.deepStrictEqual(r1, r2);
});

test('createDetectCache: invalidate() forces the next get() to re-probe', async () => {
  let probes = 0;
  const cache = createDetectCache({ now: () => 0, probe: async () => { probes++; return { present: true, running: true }; } });
  await cache.get();
  assert.strictEqual(probes, 1);
  await cache.get();                 // cached
  assert.strictEqual(probes, 1);
  cache.invalidate();
  await cache.get();                 // forced re-probe
  assert.strictEqual(probes, 2);
});

// ── late-failure mapping: docker-gone stderr → friendly copy ────────────────

test('dockerUnavailableError: daemon-down signatures → the daemon-down message', () => {
  assert.match(dockerUnavailableError('Cannot connect to the Docker daemon at unix:///…'), /daemon isn.t running/);
  assert.match(dockerUnavailableError('error during connect: ... is the docker daemon running?'), /daemon isn.t running/);
});

test('dockerUnavailableError: not-installed signatures → the not-installed message', () => {
  assert.match(dockerUnavailableError('spawn docker ENOENT'), /isn.t installed/);
  assert.match(dockerUnavailableError('docker: command not found'), /isn.t installed/);
});

test('dockerUnavailableError: a genuine compose error is NOT a docker-availability one', () => {
  assert.strictEqual(dockerUnavailableError('service "clodex" failed to build'), null);
  assert.strictEqual(dockerUnavailableError('port is already allocated'), null);
  assert.strictEqual(dockerUnavailableError(''), null);
  assert.strictEqual(dockerUnavailableError(null), null);
});

// ── manager wires the shared cache into each box (cachedAt + dedupe) ─────────

test('manager: box detect() returns the shared cached payload (stamped, deduped)', async () => {
  let probes = 0;
  const settings = fakeSettings({ boxes: [{ id: 'sandbox', label: 'sandbox', config: { ...DEFAULT_CONFIG } }] });
  const mgr = createSandboxManager({ registryDir: TMP_REGISTRY,
    getUiSettings: () => settings,
    now: () => 4242,
    spawn: () => { probes++; return fakeSpawn({ code: 0 })(); },
  });
  const box = mgr.get('sandbox');
  const d = await box.detect();
  assert.strictEqual(d.running, true);
  assert.strictEqual(d.cachedAt, 4242, 'box detect() carries the cache timestamp');
  // The manager warm-probe at creation + this call share one cached result.
  await box.detect();
  await mgr.detect();
  assert.strictEqual(probes, 1, 'the warm probe served every later reader from cache');
});

// ── factory: idempotent peer registration (settings mocked) ─────────────────

// A minimal ui-settings double: shallow-merge set, matching stores.js semantics
// for the peers array.
function fakeSettings(initial = {}) {
  let state = { peers: [], ...initial };
  return {
    _state: () => state,
    get() { return { ...state }; },
    set(partial) { state = { ...state, ...partial }; return state; },
  };
}

test('registerPeer: first call adds the sandbox row', () => {
  const settings = fakeSettings();
  let synced = 0;
  const sb = createSandbox({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, syncPeerManager: () => { synced++; } });
  sb.registerPeer(7820);
  assert.deepStrictEqual(settings._state().peers, [{ id: 'sandbox', label: 'sandbox', url: 'http://127.0.0.1:7820', inbox: 'claim' }]);
  assert.strictEqual(synced, 1);
});

test('registerPeer: an unchanged url writes nothing (no reconcile churn)', () => {
  const settings = fakeSettings({ peers: [{ id: SANDBOX_PEER_ID, label: 'sandbox', url: 'http://127.0.0.1:7820', inbox: 'claim' }] });
  let synced = 0;
  const sb = createSandbox({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, syncPeerManager: () => { synced++; } });
  sb.registerPeer(7820);
  assert.strictEqual(synced, 0);
});

test('registerPeer: a moved wire port updates the url in place, never duplicates', () => {
  const settings = fakeSettings({ peers: [
    { id: 'other', label: 'other', url: 'http://example/' },
    { id: SANDBOX_PEER_ID, label: 'sandbox', url: 'http://127.0.0.1:7820' },
  ] });
  const sb = createSandbox({ registryDir: TMP_REGISTRY, getUiSettings: () => settings });
  sb.registerPeer(7821);
  const peers = settings._state().peers;
  assert.strictEqual(peers.length, 2);
  assert.strictEqual(peers.find((p) => p.id === SANDBOX_PEER_ID).url, 'http://127.0.0.1:7821');
  assert.strictEqual(peers.find((p) => p.id === 'other').url, 'http://example/'); // untouched
});

// ── factory: up / down (spawn + settings mocked, no port probe) ─────────────

// A spawn that always reports success and never actually binds — paired with an
// isPortInUse stub so writeComposeFile's probe is deterministic and offline.
function okComposeSpawn() { return fakeSpawn({ code: 0 }); }

test('up: writes compose, brings it up, registers the peer', async () => {
  const settings = fakeSettings();
  const sb = createSandbox({
    registryDir: TMP_REGISTRY,
    spawn: okComposeSpawn(),
    getUiSettings: () => settings,
    getUserDataPath: () => TMP_USERDATA,
    isPortInUse: () => Promise.resolve(false),
    isPackaged: () => false,
    repoRoot: '/repo',
  });
  const r = await sb.up();
  assert.strictEqual(r.ok, true);
  assert.deepStrictEqual(r.ports, { web: 7810, wirescope: 7811, wire: 7820 });
  assert.strictEqual(settings._state().peers.length, 1);
  assert.strictEqual(settings._state().peers[0].id, 'sandbox');
  // The compose file was actually written to <userData>/sandbox/.
  assert.ok(fs.existsSync(sb.composePath()));
});

test('up: a non-docker compose failure surfaces raw stderr and does NOT register the peer', async () => {
  const settings = fakeSettings();
  const sb = createSandbox({ registryDir: TMP_REGISTRY,
    spawn: fakeSpawn({ code: 1, stderr: 'network timeout pulling layer sha256:abc' }),
    getUiSettings: () => settings,
    getUserDataPath: () => TMP_USERDATA,
    isPortInUse: () => Promise.resolve(false),
  });
  const r = await sb.up();
  assert.strictEqual(r.ok, false);
  assert.match(r.error, /network timeout pulling layer/);   // genuine compose error keeps its stderr
  assert.strictEqual(settings._state().peers.length, 0);
});

test('up: a docker-gone failure maps to the friendly message, invalidates the cache, no register', async () => {
  const settings = fakeSettings();
  let invalidated = 0;
  const sb = createSandbox({ registryDir: TMP_REGISTRY,
    spawn: fakeSpawn({ code: 1, stderr: 'Cannot connect to the Docker daemon at unix:///var/run/docker.sock' }),
    getUiSettings: () => settings,
    getUserDataPath: () => TMP_USERDATA,
    isPortInUse: () => Promise.resolve(false),
    invalidateDetect: () => { invalidated++; },
  });
  const r = await sb.up();
  assert.strictEqual(r.ok, false);
  assert.match(r.error, /Docker daemon isn.t running/);     // friendly copy, not raw stderr
  assert.doesNotMatch(r.error, /unix:\/\//);                // raw stderr suppressed
  assert.strictEqual(invalidated, 1, 'late failure invalidates the detect cache');
  assert.strictEqual(settings._state().peers.length, 0);
});

test('down: succeeds and leaves the peer row in place (offline affordance)', async () => {
  const settings = fakeSettings({ peers: [{ id: SANDBOX_PEER_ID, label: 'sandbox', url: 'http://127.0.0.1:7820', inbox: 'claim' }] });
  const sb = createSandbox({ registryDir: TMP_REGISTRY,
    spawn: fakeSpawn({ code: 0 }),
    getUiSettings: () => settings,
    getUserDataPath: () => TMP_USERDATA,
  });
  const r = await sb.down();
  assert.strictEqual(r.ok, true);
  assert.strictEqual(settings._state().peers.length, 1); // NOT removed
});

test('down: keeps the box state dir — surviving a stop IS the durability', async () => {
  const reg = fs.mkdtempSync(path.join(TMP_USERDATA, 'reg-'));
  const sb = createSandbox({
    spawn: fakeSpawn({ code: 0 }),
    getUiSettings: () => fakeSettings(),
    getUserDataPath: () => TMP_USERDATA,
    registryDir: reg,
  });
  const ticket = path.join(sb.stateDir(), 'dot', 'tickets.json');
  fs.mkdirSync(path.dirname(ticket), { recursive: true });
  fs.writeFileSync(ticket, '[]');
  assert.strictEqual((await sb.down()).ok, true);
  assert.ok(fs.existsSync(ticket), 'a stop must not drop the box\'s seats and tickets');
});

// ── factory: rebuild (image-kind branch, spawn + settings mocked) ───────────

// A spawn recording the compose subcommand of every invocation, so a test can
// assert the exact docker compose arg vector rebuild chose. `results` maps the
// first non-flag compose word (up/pull/…) to a fakeSpawn behavior; unmatched
// commands succeed. detect ('info') and any others fall through to code 0.
function recordingSpawn(calls, results = {}) {
  return (_cmd, args) => {
    calls.push(args);
    // args = ['compose','-p',<project>,'-f',<path>, <sub…>] for compose calls;
    // the subcommand is the token right after the `-f <path>` pair.
    const f = args.indexOf('-f');
    const sub = f >= 0 ? args[f + 2] : args[0];
    const behavior = results[sub] || { code: 0 };
    return fakeSpawn(behavior)();
  };
}

test('rebuild: dev build kind uses `up -d --build`, then registers the peer', async () => {
  const settings = fakeSettings();
  const calls = [];
  const sb = createSandbox({ registryDir: TMP_REGISTRY,
    spawn: recordingSpawn(calls),
    getUiSettings: () => settings,
    getUserDataPath: () => TMP_USERDATA,
    isPortInUse: () => Promise.resolve(false),
    isPackaged: () => false,   // dev checkout → resolveImage kind 'build'
    repoRoot: '/repo',
  });
  const r = await sb.rebuild();
  assert.strictEqual(r.ok, true);
  assert.deepStrictEqual(r.ports, { web: 7810, wirescope: 7811, wire: 7820 });
  // Exactly one compose invocation: up -d --build (no pull in the build path).
  const composeCalls = composeSubcommands(calls);
  assert.deepStrictEqual(composeCalls, [['up', '-d', '--build']]);
  assert.strictEqual(settings._state().peers.length, 1);
  assert.strictEqual(settings._state().peers[0].id, 'sandbox');
});

test('rebuild: packaged pinned image kind pulls then `up -d`', async () => {
  const settings = fakeSettings();
  const calls = [];
  const sb = createSandbox({ registryDir: TMP_REGISTRY,
    spawn: recordingSpawn(calls),
    getUiSettings: () => settings,
    getUserDataPath: () => TMP_USERDATA,
    isPortInUse: () => Promise.resolve(false),
    isPackaged: () => true,   // packaged → resolveImage kind 'image' (GHCR tag)
    appVersion: '9.9.9',
  });
  const r = await sb.rebuild();
  assert.strictEqual(r.ok, true);
  const composeCalls = composeSubcommands(calls);
  assert.deepStrictEqual(composeCalls, [['pull'], ['up', '-d']]);
  assert.strictEqual(settings._state().peers.length, 1);
});

test('rebuild: a failed pull surfaces stderr, skips up, and does NOT register the peer', async () => {
  const settings = fakeSettings();
  const calls = [];
  const sb = createSandbox({ registryDir: TMP_REGISTRY,
    spawn: recordingSpawn(calls, { pull: { code: 1, stderr: 'manifest unknown' } }),
    getUiSettings: () => settings,
    getUserDataPath: () => TMP_USERDATA,
    isPortInUse: () => Promise.resolve(false),
    isPackaged: () => true,
    appVersion: '9.9.9',
  });
  const r = await sb.rebuild();
  assert.strictEqual(r.ok, false);
  assert.match(r.error, /manifest unknown/);
  // pull ran; up did NOT.
  const composeCalls = composeSubcommands(calls);
  assert.deepStrictEqual(composeCalls, [['pull']]);
  assert.strictEqual(settings._state().peers.length, 0);
});

test('rebuild: a build failure surfaces stderr and does NOT register the peer', async () => {
  const settings = fakeSettings();
  const sb = createSandbox({ registryDir: TMP_REGISTRY,
    spawn: fakeSpawn({ code: 1, stderr: 'failed to solve: dockerfile' }),
    getUiSettings: () => settings,
    getUserDataPath: () => TMP_USERDATA,
    isPortInUse: () => Promise.resolve(false),
    isPackaged: () => false,
    repoRoot: '/repo',
  });
  const r = await sb.rebuild();
  assert.strictEqual(r.ok, false);
  assert.match(r.error, /failed to solve/);
  assert.strictEqual(settings._state().peers.length, 0);
});

// ── factory: re-up port stability (the self-collision fix) ──────────────────

// A userData dir unique to a test, so its compose.yaml doesn't cross-talk.
function freshUserData() {
  return fs.mkdtempSync(path.join(TMP_USERDATA, 'ud-'));
}

test('up twice with our own ports "busy" keeps the three ports byte-stable', async () => {
  const settings = fakeSettings();
  const ud = freshUserData();
  // After the first up publishes 7810/7811/7820, a live probe would see them
  // busy — the exact self-collision that used to drift the ports upward.
  const ownBusy = new Set([7810, 7811, 7820]);
  let started = false;
  const sb = createSandbox({ registryDir: TMP_REGISTRY,
    spawn: okComposeSpawn(),
    getUiSettings: () => settings,
    getUserDataPath: () => ud,
    isPortInUse: (p) => Promise.resolve(started && ownBusy.has(p)),
  });
  const first = await sb.up();
  const composeA = fs.readFileSync(sb.composePath(), 'utf8');
  started = true; // container is now "running" — its ports read busy
  const second = await sb.up();
  const composeB = fs.readFileSync(sb.composePath(), 'utf8');

  assert.deepStrictEqual(first.ports, { web: 7810, wirescope: 7811, wire: 7820 });
  assert.deepStrictEqual(second.ports, { web: 7810, wirescope: 7811, wire: 7820 });
  assert.strictEqual(composeA, composeB); // byte-identical regen
  // The peer url did NOT churn (one row, unchanged url).
  assert.strictEqual(settings._state().peers.length, 1);
  assert.strictEqual(settings._state().peers[0].url, 'http://127.0.0.1:7820');
});

test('up: a GENUINE squatter on 7810 (not our own port) still bumps', async () => {
  const settings = fakeSettings();
  const ud = freshUserData();
  // 7810 is held by something that is NOT our container (no prior compose file).
  const sb = createSandbox({ registryDir: TMP_REGISTRY,
    spawn: okComposeSpawn(),
    getUiSettings: () => settings,
    getUserDataPath: () => ud,
    isPortInUse: (p) => Promise.resolve(p === 7810),
  });
  const r = await sb.up();
  assert.strictEqual(r.ports.web, 7811); // bumped off the squatter
  assert.strictEqual(settings._state().peers[0].url, `http://127.0.0.1:${r.ports.wire}`);
});

test('status: exposes effective (bumped) ports while running, omits them when stopped', async () => {
  const settings = fakeSettings();
  const ud = freshUserData();
  // A genuine squatter on 7810 forces the box off the configured default — the
  // exact bug #4 shape (box 2 running on a bumped port).
  const sbUp = createSandbox({ registryDir: TMP_REGISTRY,
    spawn: recordingSpawn([], { ps: { code: 0, stdout: '[{"Service":"clodex","State":"running"}]' } }),
    getUiSettings: () => settings,
    getUserDataPath: () => ud,
    isPortInUse: (p) => Promise.resolve(p === 7810),
  });
  await sbUp.up(); // writes the compose file publishing the bumped ports
  const running = await sbUp.status();
  assert.strictEqual(running.state, 'running');
  // status.ports mirrors what the compose file actually publishes (effective, not
  // configured) — and the web port really did bump off 7810.
  assert.deepStrictEqual(running.ports, parseOwnPortMap(fs.readFileSync(sbUp.composePath(), 'utf8')));
  assert.ok(running.ports.web && running.ports.web !== 7810);

  // Same compose file on disk, but the container is stopped → no effective ports
  // (the file persists but describes no live listener; Start regenerates them).
  const sbStopped = createSandbox({ registryDir: TMP_REGISTRY,
    spawn: recordingSpawn([], { ps: { code: 0, stdout: '[{"Service":"clodex","State":"exited"}]' } }),
    getUiSettings: () => settings,
    getUserDataPath: () => ud,
    isPortInUse: () => Promise.resolve(false),
  });
  const stopped = await sbStopped.status();
  assert.strictEqual(stopped.state, 'exited');
  assert.strictEqual(stopped.ports, undefined);
});

// ── factory: auth token file (M4) ───────────────────────────────────────────

test('setAuthToken: writes auth.env at mode 0600 with the CLAUDE_CODE_OAUTH_TOKEN line', () => {
  const ud = freshUserData();
  const sb = createSandbox({ registryDir: TMP_REGISTRY, getUiSettings: () => fakeSettings(), getUserDataPath: () => ud });
  const r = sb.setAuthToken('sk-tok-123');
  assert.deepStrictEqual(r, { ok: true, hasToken: true });
  const file = path.join(ud, 'sandbox', 'auth.env');
  assert.strictEqual(fs.readFileSync(file, 'utf8'), 'CLAUDE_CODE_OAUTH_TOKEN=sk-tok-123\n');
  assert.strictEqual(fs.statSync(file).mode & 0o777, 0o600);
  assert.strictEqual(sb.hasAuthToken(), true);
});

// t808: the peer-wire secret is what a team's seats authenticate to the box
// with, and `[agent:team sandbox up]` copies it into the team's sandbox.json.
// Without this export that verb has no token to write — and the handler's own
// suite cannot see the gap, since its fake box supplies one either way.
test('remoteToken: exposed on the box, and it IS the CLODEX_REMOTE_TOKEN in auth.env', () => {
  const ud = freshUserData();
  const sb = createSandbox({ registryDir: TMP_REGISTRY, getUiSettings: () => fakeSettings(), getUserDataPath: () => ud });

  assert.strictEqual(typeof sb.remoteToken, 'function', 'the main process can read the box secret');
  assert.strictEqual(sb.remoteToken(), null, 'nothing provisioned yet → no token to hand out');

  fs.mkdirSync(path.join(ud, 'sandbox'), { recursive: true });
  fs.writeFileSync(path.join(ud, 'sandbox', 'auth.env'), 'CLODEX_REMOTE_TOKEN=tok-abc-123\n');
  assert.strictEqual(sb.remoteToken(), 'tok-abc-123', 'it reads the SAME line registerPeer authenticates with');
});

// The other half of that boundary: reading the secret is a main-process
// capability, so no `sandbox:*` IPC channel may forward it to the renderer.
test('remoteToken: no ipc-handlers sandbox channel exposes it', () => {
  const src = fs.readFileSync(path.join(__dirname, '..', 'ipc-handlers.js'), 'utf8');
  assert.ok(!/remoteToken/.test(src),
    'ipc-handlers.js names remoteToken — the peer-wire secret must not cross to the renderer');
});

test('setAuthToken: trims surrounding whitespace from a pasted token', () => {
  const ud = freshUserData();
  const sb = createSandbox({ registryDir: TMP_REGISTRY, getUiSettings: () => fakeSettings(), getUserDataPath: () => ud });
  sb.setAuthToken('  sk-pasted\n');
  const file = path.join(ud, 'sandbox', 'auth.env');
  assert.strictEqual(fs.readFileSync(file, 'utf8'), 'CLAUDE_CODE_OAUTH_TOKEN=sk-pasted\n');
});

test('setAuthToken: an empty/blank/null token is rejected and writes no file', () => {
  const ud = freshUserData();
  const sb = createSandbox({ registryDir: TMP_REGISTRY, getUiSettings: () => fakeSettings(), getUserDataPath: () => ud });
  assert.strictEqual(sb.setAuthToken('   ').ok, false);
  assert.strictEqual(sb.setAuthToken('').ok, false);
  assert.strictEqual(sb.setAuthToken(null).ok, false);
  assert.strictEqual(sb.hasAuthToken(), false);
});

test('getConfig.hasToken tracks the auth.env file; setConfig never persists it', () => {
  const ud = freshUserData();
  const settings = fakeSettings();
  const sb = createSandbox({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, getUserDataPath: () => ud });
  assert.strictEqual(sb.getConfig().hasToken, false);
  sb.setAuthToken('sk-x');
  assert.strictEqual(sb.getConfig().hasToken, true);
  // Persisting other config must not leak the derived flag into the store.
  sb.setConfig({ webPort: 7999 });
  assert.strictEqual('hasToken' in settings._state().sandbox, false);
});

test('clearAuthToken: deletes the file, idempotent when already absent', () => {
  const ud = freshUserData();
  const sb = createSandbox({ registryDir: TMP_REGISTRY, getUiSettings: () => fakeSettings(), getUserDataPath: () => ud });
  sb.setAuthToken('sk-y');
  assert.strictEqual(sb.hasAuthToken(), true);
  assert.deepStrictEqual(sb.clearAuthToken(), { ok: true, hasToken: false });
  assert.strictEqual(sb.hasAuthToken(), false);
  assert.deepStrictEqual(sb.clearAuthToken(), { ok: true, hasToken: false }); // no-op, still ok
});

test('writeComposeFile: references the auth env_file once the token exists, never the value', async () => {
  const ud = freshUserData();
  const sb = createSandbox({ registryDir: TMP_REGISTRY,
    getUiSettings: () => fakeSettings(),
    getUserDataPath: () => ud,
    isPortInUse: () => Promise.resolve(false),
  });
  // No token yet → no env_file line.
  await sb.writeComposeFile();
  let yaml = fs.readFileSync(sb.composePath(), 'utf8');
  assert.doesNotMatch(yaml, /env_file/);
  // Seed the token → next regen references the file by path; the secret value
  // (and the var name it's keyed under) never appear in the compose bytes.
  sb.setAuthToken('sk-secret-should-never-appear');
  await sb.writeComposeFile();
  yaml = fs.readFileSync(sb.composePath(), 'utf8');
  const authPath = path.join(ud, 'sandbox', 'auth.env');
  assert.ok(yaml.includes('env_file:'));
  // Quoted like the workDir bind — userData paths carry spaces on macOS.
  assert.ok(yaml.includes(`- "${authPath}"`));
  assert.doesNotMatch(yaml, /sk-secret-should-never-appear/);
  assert.doesNotMatch(yaml, /CLAUDE_CODE_OAUTH_TOKEN/);
});

test('writeComposeFile: ensure-dirs the host library sources and binds them read-only', async () => {
  const ud = freshUserData();
  const reg = fs.mkdtempSync(path.join(TMP_USERDATA, 'reg-'));
  const sb = createSandbox({ registryDir: TMP_REGISTRY,
    getUiSettings: () => fakeSettings(),
    getUserDataPath: () => ud,
    registryDir: reg,
    isPortInUse: () => Promise.resolve(false),
  });
  await sb.writeComposeFile();
  // The three source dirs were created under the injected host registry root,
  // so docker never binds a missing source.
  for (const d of ['skills', 'agents', 'library']) {
    assert.ok(fs.existsSync(path.join(reg, d)), `${d} ensure-dir'd`);
  }
  // And the compose bytes bind them read-only into the box.
  const yaml = fs.readFileSync(sb.composePath(), 'utf8');
  assert.ok(yaml.includes(`- "${path.join(reg, 'skills')}:/home/clodex/.clodex/skills:ro"`));
  assert.ok(yaml.includes(`- "${path.join(reg, 'agents')}:/home/clodex/.clodex/agents:ro"`));
  assert.ok(yaml.includes(`- "${path.join(reg, 'library')}:/home/clodex/.clodex/library:ro"`));
});

test('writeComposeFile: creates the box state dirs 0700 under <registryDir>/boxes/<id> and binds them', async () => {
  const ud = freshUserData();
  const reg = fs.mkdtempSync(path.join(TMP_USERDATA, 'reg-'));
  const sb = createSandbox({
    getUiSettings: () => fakeSettings(),
    getUserDataPath: () => ud,
    registryDir: reg,
    isPortInUse: () => Promise.resolve(false),
  });
  await sb.writeComposeFile();
  const base = path.join(reg, 'boxes', SANDBOX_PEER_ID);
  assert.strictEqual(sb.stateDir(), base);
  for (const d of ['data', 'dot', 'claude']) {
    const dir = path.join(base, d);
    assert.ok(fs.existsSync(dir), `${d} created`);
    assert.strictEqual(fs.statSync(dir).mode & 0o777, 0o700, `${d} is 0700`);
  }
  const yaml = fs.readFileSync(sb.composePath(), 'utf8');
  assert.ok(yaml.includes(`- "${path.join(base, 'data')}:/data"`));
  assert.ok(yaml.includes(`- "${path.join(base, 'dot')}:/home/clodex/.clodex"`));
  assert.ok(yaml.includes(`- "${path.join(base, 'claude')}:/home/clodex/.claude"`));
});

test('source shape: every factory call in this file injects a registryDir (never the real ~/.clodex)', () => {
  const src = fs.readFileSync(__filename, 'utf8');
  const re = /create(?:Sandbox|SandboxManager)\(\{/g;
  const missing = [];
  let seen = 0;
  let m;
  while ((m = re.exec(src))) {
    let i = m.index + m[0].length - 1;
    let depth = 0;
    do {
      if (src[i] === '{') depth++;
      else if (src[i] === '}') depth--;
      i++;
    } while (depth > 0 && i < src.length);
    seen++;
    if (!src.slice(m.index, i).includes('registryDir')) {
      missing.push(src.slice(0, m.index).split('\n').length);
    }
  }
  assert.ok(seen >= 50, `expected every factory call site, scanned ${seen}`);
  assert.deepStrictEqual(missing, [],
    `factory calls without a registryDir would mkdir/rmSync the operator's real ~/.clodex/boxes — lines ${missing.join(', ')}`);
});

// ── factory: remote-wire token auto-provision (remote-auth chunk 4) ──────────

test('up: auto-provisions CLODEX_REMOTE_TOKEN into auth.env, compose stays token-clean, peer carries the Bearer', async () => {
  const ud = freshUserData();
  const settings = fakeSettings();
  const sb = createSandbox({ registryDir: TMP_REGISTRY,
    spawn: okComposeSpawn(),
    getUiSettings: () => settings,
    getUserDataPath: () => ud,
    isPortInUse: () => Promise.resolve(false),
  });
  const r = await sb.up();
  assert.strictEqual(r.ok, true);

  // A random hex secret landed in the 0600 auth.env under its own key.
  const authFile = path.join(ud, 'sandbox', 'auth.env');
  const authBody = fs.readFileSync(authFile, 'utf8');
  assert.match(authBody, /^CLODEX_REMOTE_TOKEN=[0-9a-f]{64}$/m);
  assert.strictEqual(fs.statSync(authFile).mode & 0o777, 0o600);
  const token = authBody.match(/CLODEX_REMOTE_TOKEN=([0-9a-f]+)/)[1];

  // The compose bytes reference only the env_file — never the key name or value
  // (env_file injects it into the container env, so no compose `environment:` line
  // is needed). This is the chunk-4 leak-guard.
  const yaml = fs.readFileSync(sb.composePath(), 'utf8');
  assert.ok(yaml.includes('env_file:'));
  assert.doesNotMatch(yaml, /CLODEX_REMOTE_TOKEN/);
  assert.ok(!yaml.includes(token), 'the secret value never appears in the compose bytes');

  // The desktop-side sandbox peer entry carries the same token as its Bearer.
  assert.strictEqual(settings._state().peers[0].id, SANDBOX_PEER_ID);
  assert.strictEqual(settings._state().peers[0].token, token);
});

test('up twice: the remote token (and the peer Bearer) stay stable — provisioned once, never rerolled', async () => {
  const ud = freshUserData();
  const settings = fakeSettings();
  const sb = createSandbox({ registryDir: TMP_REGISTRY,
    spawn: okComposeSpawn(),
    getUiSettings: () => settings,
    getUserDataPath: () => ud,
    isPortInUse: () => Promise.resolve(false),
  });
  await sb.up();
  const first = fs.readFileSync(path.join(ud, 'sandbox', 'auth.env'), 'utf8');
  await sb.up();
  const second = fs.readFileSync(path.join(ud, 'sandbox', 'auth.env'), 'utf8');
  assert.strictEqual(first, second, 'the token is idempotent across re-up');
  // One peer row, unchanged token — no reconcile churn from a re-roll.
  assert.strictEqual(settings._state().peers.length, 1);
  assert.match(settings._state().peers[0].token, /^[0-9a-f]{64}$/);
});

test('setAuthToken preserves an existing remote token line (multi-key write)', async () => {
  const ud = freshUserData();
  const settings = fakeSettings();
  const sb = createSandbox({ registryDir: TMP_REGISTRY,
    spawn: okComposeSpawn(),
    getUiSettings: () => settings,
    getUserDataPath: () => ud,
    isPortInUse: () => Promise.resolve(false),
  });
  // up() provisions the remote token first.
  await sb.up();
  const authFile = path.join(ud, 'sandbox', 'auth.env');
  const remote = fs.readFileSync(authFile, 'utf8').match(/CLODEX_REMOTE_TOKEN=([0-9a-f]+)/)[1];

  // Now the operator sets an OAuth token — the remote token must survive.
  assert.deepStrictEqual(sb.setAuthToken('sk-oauth-added'), { ok: true, hasToken: true });
  let body = fs.readFileSync(authFile, 'utf8');
  assert.match(body, /^CLAUDE_CODE_OAUTH_TOKEN=sk-oauth-added$/m);
  assert.match(body, new RegExp(`^CLODEX_REMOTE_TOKEN=${remote}$`, 'm'));

  // Clearing the OAuth token leaves the remote token (and hence the file) intact.
  assert.deepStrictEqual(sb.clearAuthToken(), { ok: true, hasToken: false });
  assert.strictEqual(sb.hasAuthToken(), false);
  body = fs.readFileSync(authFile, 'utf8');
  assert.doesNotMatch(body, /CLAUDE_CODE_OAUTH_TOKEN/);
  assert.match(body, new RegExp(`^CLODEX_REMOTE_TOKEN=${remote}$`, 'm'));
});

// ── composeProjectName (per-box volume namespace, M6b P2) ───────────────────

test('composeProjectName: passes a valid id through, coerces junk, falls back', () => {
  assert.strictEqual(composeProjectName('sandbox'), 'sandbox');
  assert.strictEqual(composeProjectName('proj-1_x'), 'proj-1_x');
  // Uppercase/dots/spaces are coerced to the compose charset (defensive — ids are
  // already gated at create, but -p must never emit an invalid project name).
  assert.strictEqual(composeProjectName('My.Proj Box'), 'my-proj-box');
  assert.strictEqual(composeProjectName(''), 'sandbox');
  assert.strictEqual(composeProjectName('---'), 'sandbox');
});

// ── manager: N instances behind one Map (M6b P1) ────────────────────────────

// A ui-settings double carrying a `boxes` registry, shallow-merge set like the
// peers double above. Seeded with whatever rows a test needs.
function fakeBoxSettings(boxes) {
  let state = { peers: [], boxes };
  return {
    _state: () => state,
    get() { return { ...state }; },
    set(partial) { state = { ...state, ...partial }; return state; },
  };
}

test('manager: get() resolves the shared box by default and memoizes the instance', () => {
  const settings = fakeBoxSettings([{ id: 'sandbox', label: 'sandbox', config: {} }]);
  const mgr = createSandboxManager({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, getUserDataPath: () => TMP_USERDATA });
  const a = mgr.get();          // default → 'sandbox'
  const b = mgr.get('sandbox');
  assert.ok(a, 'shared box resolves');
  assert.strictEqual(a.id, 'sandbox');
  assert.strictEqual(a, b, 'same id returns the memoized instance');
});

test('manager: get() returns null for an unknown box id', () => {
  const settings = fakeBoxSettings([{ id: 'sandbox', label: 'sandbox', config: {} }]);
  const mgr = createSandboxManager({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, getUserDataPath: () => TMP_USERDATA });
  assert.strictEqual(mgr.get('nope'), null);
});

test('manager: list() reports every registry row as { id, label }', () => {
  const settings = fakeBoxSettings([
    { id: 'sandbox', label: 'sandbox', config: {} },
    { id: 'proj', label: 'My Project', config: {} },
  ]);
  const mgr = createSandboxManager({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, getUserDataPath: () => TMP_USERDATA });
  assert.deepStrictEqual(mgr.list(), [
    { id: 'sandbox', label: 'sandbox' },
    { id: 'proj', label: 'My Project' },
  ]);
});

test('manager: each instance reads/writes its OWN registry row config', () => {
  const settings = fakeBoxSettings([
    { id: 'sandbox', label: 'sandbox', config: { webPort: 7810 } },
    { id: 'proj', label: 'proj', config: { webPort: 7830 } },
  ]);
  const mgr = createSandboxManager({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, getUserDataPath: () => TMP_USERDATA });
  assert.strictEqual(mgr.get('sandbox').getConfig().webPort, 7810);
  assert.strictEqual(mgr.get('proj').getConfig().webPort, 7830);
  // A write on one box lands on that box's row only, never the other's.
  mgr.get('proj').setConfig({ autoStart: true });
  const rows = Object.fromEntries(settings._state().boxes.map((b) => [b.id, b.config]));
  assert.strictEqual(rows.proj.autoStart, true);
  assert.strictEqual(rows.sandbox.autoStart, undefined);
});

test('manager: a box compose dir is per-id (basename ⇒ compose project ⇒ volume namespace)', () => {
  const settings = fakeBoxSettings([
    { id: 'sandbox', label: 'sandbox', config: {} },
    { id: 'proj', label: 'proj', config: {} },
  ]);
  const mgr = createSandboxManager({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, getUserDataPath: () => '/ud' });
  // Shared box keeps the legacy `sandbox` dir (byte-stable); others get sandbox-<id>.
  assert.strictEqual(mgr.get('sandbox').sandboxDir(), path.join('/ud', 'sandbox'));
  assert.strictEqual(mgr.get('proj').sandboxDir(), path.join('/ud', 'sandbox-proj'));
});

test('manager: two boxes up() → two managed peer rows, isolated auth.env + hostname', async () => {
  const ud = freshUserData();
  const settings = fakeBoxSettings([
    { id: 'sandbox', label: 'sandbox', config: {} },
    { id: 'proj', label: 'proj', config: { webPort: 7830, wirescopePort: 7831, wirePort: 7840 } },
  ]);
  const calls = [];
  const mgr = createSandboxManager({ registryDir: TMP_REGISTRY,
    spawn: recordingSpawn(calls),
    getUiSettings: () => settings,
    getUserDataPath: () => ud,
    isPortInUse: () => Promise.resolve(false),
    isPackaged: () => false,
    repoRoot: '/repo',
  });
  const r1 = await mgr.get('sandbox').up();
  const r2 = await mgr.get('proj').up();
  assert.strictEqual(r1.ok, true);
  assert.strictEqual(r2.ok, true);

  // Each box's compose invocations carry its own -p project name (volume namespace).
  const projFlags = calls.filter((a) => a.includes('compose')).map((a) => a[a.indexOf('-p') + 1]);
  assert.ok(projFlags.includes('sandbox') && projFlags.includes('proj'), 'both -p projects seen');

  // Two distinct managed peer rows keyed by box id.
  const peers = Object.fromEntries(settings._state().peers.map((p) => [p.id, p]));
  assert.ok(peers.sandbox && peers.proj, 'both boxes registered a peer');
  assert.strictEqual(peers.proj.label, 'proj');
  assert.notStrictEqual(peers.sandbox.url, peers.proj.url);

  // Per-box auth.env (own remote token) under the per-box compose dir.
  const sharedAuth = fs.readFileSync(path.join(ud, 'sandbox', 'auth.env'), 'utf8');
  const projAuth = fs.readFileSync(path.join(ud, 'sandbox-proj', 'auth.env'), 'utf8');
  const sharedTok = sharedAuth.match(/CLODEX_REMOTE_TOKEN=([0-9a-f]+)/)[1];
  const projTok = projAuth.match(/CLODEX_REMOTE_TOKEN=([0-9a-f]+)/)[1];
  assert.notStrictEqual(sharedTok, projTok, 'each box mints its own remote token');
  assert.strictEqual(peers.sandbox.token, sharedTok);
  assert.strictEqual(peers.proj.token, projTok);

  // Each box's compose bytes carry its own hostname (its wire SELF_LABEL).
  assert.match(fs.readFileSync(path.join(ud, 'sandbox', 'compose.yaml'), 'utf8'), /^ {4}hostname: sandbox$/m);
  assert.match(fs.readFileSync(path.join(ud, 'sandbox-proj', 'compose.yaml'), 'utf8'), /^ {4}hostname: proj$/m);
});

test('manager: create() mints a box row from DEFAULT_CONFIG, gated to the tight charset', () => {
  const settings = fakeBoxSettings([{ id: 'sandbox', label: 'sandbox', config: {} }]);
  const mgr = createSandboxManager({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, getUserDataPath: () => TMP_USERDATA });
  const r = mgr.create('proj-1', 'My Project');
  assert.deepStrictEqual(r, { ok: true, box: { id: 'proj-1', label: 'My Project' } });
  const row = settings._state().boxes.find((b) => b.id === 'proj-1');
  assert.strictEqual(row.label, 'My Project');
  assert.deepStrictEqual(row.config, DEFAULT_CONFIG);
  // Now resolvable through get().
  assert.strictEqual(mgr.get('proj-1').id, 'proj-1');
});

test('manager: create() rejects a bad charset, a dup, and the shared id; label falls back to id', () => {
  const settings = fakeBoxSettings([{ id: 'sandbox', label: 'sandbox', config: {} }]);
  const mgr = createSandboxManager({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, getUserDataPath: () => TMP_USERDATA });
  assert.match(mgr.create('Bad.Id').error, /lowercase/);      // uppercase + dot
  assert.match(mgr.create('has space').error, /lowercase/);
  assert.match(mgr.create('sandbox').error, /already exists/); // shared id is taken
  mgr.create('dup');
  assert.match(mgr.create('dup').error, /already exists/);
  // A blank label defaults to the id.
  assert.strictEqual(mgr.create('bare').box.label, 'bare');
});

test("manager: create() rejects the reserved 'host' id (placement collision, M6b P3)", () => {
  const settings = fakeBoxSettings([{ id: 'sandbox', label: 'sandbox', config: {} }]);
  const mgr = createSandboxManager({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, getUserDataPath: () => TMP_USERDATA });
  // 'host' passes BOX_ID_RE but is reserved for the New Session placement selector's
  // "This Mac" value — a box named 'host' would be unaddressable. Rejected, no row added.
  const r = mgr.create('host', 'Host');
  assert.strictEqual(r.ok, false);
  assert.match(r.error, /reserved/);
  assert.strictEqual(settings._state().boxes.some((b) => b.id === 'host'), false);
  assert.strictEqual(mgr.get('host'), null);
});

test('manager: remove() stops the box, drops its peer row + registry row, keeps others', async () => {
  const ud = freshUserData();
  const settings = fakeBoxSettings([
    { id: 'sandbox', label: 'sandbox', config: {} },
    { id: 'proj', label: 'proj', config: {} },
  ]);
  let synced = 0;
  const calls = [];
  const mgr = createSandboxManager({ registryDir: TMP_REGISTRY,
    spawn: recordingSpawn(calls),
    getUiSettings: () => settings,
    getUserDataPath: () => ud,
    isPortInUse: () => Promise.resolve(false),
    isPackaged: () => false,
    repoRoot: '/repo',
    syncPeerManager: () => { synced++; },
  });
  // Bring proj up so it has a peer row to drop.
  await mgr.get('proj').up();
  assert.ok(settings._state().peers.find((p) => p.id === 'proj'), 'proj registered');
  synced = 0;

  const r = await mgr.remove('proj');
  assert.strictEqual(r.ok, true);
  // Container stopped (a compose `down` ran), peer row + registry row gone.
  const composeCalls = composeSubcommands(calls);
  assert.ok(composeCalls.some((c) => c[0] === 'down'), 'down was invoked');
  assert.strictEqual(settings._state().peers.find((p) => p.id === 'proj'), undefined);
  assert.strictEqual(settings._state().boxes.find((b) => b.id === 'proj'), undefined);
  assert.ok(settings._state().boxes.find((b) => b.id === 'sandbox'), 'shared box untouched');
  assert.ok(synced > 0, 'peer manager reconciled after the row drop');
  // The instance is de-memoized; get() re-null now the row is gone.
  assert.strictEqual(mgr.get('proj'), null);
});

test('manager: remove() deletes the box state dir, and nothing above it', async () => {
  const reg = fs.mkdtempSync(path.join(TMP_USERDATA, 'reg-'));
  const settings = fakeBoxSettings([{ id: 'proj', label: 'proj', config: {} }]);
  const mgr = createSandboxManager({
    spawn: recordingSpawn([]),
    getUiSettings: () => settings,
    getUserDataPath: () => TMP_USERDATA,
    registryDir: reg,
    isPortInUse: () => Promise.resolve(false),
  });
  const dir = mgr.get('proj').stateDir();
  fs.mkdirSync(path.join(dir, 'dot'), { recursive: true });
  assert.strictEqual(path.dirname(dir), path.join(reg, 'boxes'));
  const r = await mgr.remove('proj');
  assert.strictEqual(r.ok, true);
  assert.strictEqual(fs.existsSync(dir), false, 'the state folder goes with the box');
  assert.ok(fs.existsSync(path.join(reg, 'boxes')), 'the boxes root itself is untouched');
});

test('manager: remove() deletes ANY box including the default \'sandbox\', refuses only unknown ids', async () => {
  // 'sandbox' has no special status (M6b P2) — it deletes like any other box.
  const settings = fakeBoxSettings([{ id: 'sandbox', label: 'sandbox', config: {} }]);
  const mgr = createSandboxManager({ registryDir: TMP_REGISTRY,
    spawn: recordingSpawn([]),
    getUiSettings: () => settings,
    getUserDataPath: () => TMP_USERDATA,
    isPortInUse: () => Promise.resolve(false),
  });
  const r = await mgr.remove('sandbox');
  assert.strictEqual(r.ok, true);
  assert.deepStrictEqual(settings._state().boxes, [], 'the default box is gone — registry now empty');
  assert.strictEqual(mgr.get('sandbox'), null, 'no reseed; get() is null with an empty registry');
  // An unknown id is still refused.
  assert.match((await mgr.remove('ghost')).error, /no such sandbox/);
});

test('unregisterPeer: drops this box\'s row only, no-op when already absent', () => {
  const settings = fakeSettings({ peers: [
    { id: 'sandbox', label: 'sandbox', url: 'http://a' },
    { id: 'proj', label: 'proj', url: 'http://b' },
  ] });
  let synced = 0;
  const sb = createSandbox({ registryDir: TMP_REGISTRY, getUiSettings: () => settings, id: 'proj', syncPeerManager: () => { synced++; } });
  sb.unregisterPeer();
  assert.deepStrictEqual(settings._state().peers.map((p) => p.id), ['sandbox']);
  assert.strictEqual(synced, 1);
  sb.unregisterPeer();   // already gone → no write, no churn
  assert.strictEqual(synced, 1);
});

test('manager: bringUp is serialized across instances (shared chain, no probe race)', async () => {
  const settings = fakeBoxSettings([
    { id: 'sandbox', label: 'sandbox', config: {} },
    { id: 'proj', label: 'proj', config: {} },
  ]);
  // Track how many bringUps are mid-flight at once via a probe that yields the
  // event loop — if the chain works, it's never > 1.
  let inFlight = 0, maxInFlight = 0;
  const mgr = createSandboxManager({ registryDir: TMP_REGISTRY,
    spawn: okComposeSpawn(),
    getUiSettings: () => settings,
    getUserDataPath: () => freshUserData(),
    isPortInUse: async () => { inFlight++; maxInFlight = Math.max(maxInFlight, inFlight); await Promise.resolve(); inFlight--; return false; },
    isPackaged: () => false,
    repoRoot: '/repo',
  });
  await Promise.all([mgr.get('sandbox').up(), mgr.get('proj').up()]);
  assert.strictEqual(maxInFlight, 1, 'the two bringUps never overlapped');
});

// ── tracked git ref (t807) ──────────────────────────────────────────────────
//
// A box with `ref` set builds from a DETACHED worktree of the Clodex checkout at
// that commit, rather than from the live checkout (dev) or the GHCR tag
// (packaged). These tests drive real git against a temp repo — the whole point
// of the feature is what git does, and a mocked git would pin only the arg
// vectors, which is the half that was never in doubt.

const { execFileSync } = require('node:child_process');
const { removeWorktree } = require('../git-worktree');

function gitIn(dir, args) {
  return execFileSync('git', ['-C', dir, ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
}

// A repo with one commit on `master` and a file whose content identifies the
// commit, so a test can tell WHICH commit the src worktree is parked on without
// comparing shas by hand.
function tempRepo(marker = 'one') {
  const dir = fs.mkdtempSync(path.join(TMP_USERDATA, 'repo-'));
  gitIn(dir, ['init', '-q', '-b', 'master']);
  gitIn(dir, ['config', 'user.name', 'Clodex']);
  gitIn(dir, ['config', 'user.email', 'clodex@localhost']);
  fs.writeFileSync(path.join(dir, 'marker.txt'), marker);
  gitIn(dir, ['add', '-A']);
  gitIn(dir, ['commit', '-q', '-m', marker]);
  return dir;
}

function commitOn(repo, branch, marker) {
  gitIn(repo, ['checkout', '-q', branch]);
  fs.writeFileSync(path.join(repo, 'marker.txt'), marker);
  gitIn(repo, ['add', '-A']);
  gitIn(repo, ['commit', '-q', '-m', marker]);
  return gitIn(repo, ['rev-parse', 'HEAD']);
}

// Every temp repo grows worktrees under a temp userData; both live inside
// TMP_USERDATA, which the process-exit hook removes wholesale. The git ADMIN
// entries live in the repo, which goes with it.
function refSandbox(repo, extra = {}) {
  const settings = fakeSettings();
  const ud = freshUserData();
  const sb = createSandbox({ registryDir: TMP_REGISTRY,
    spawn: okComposeSpawn(),
    getUiSettings: () => settings,
    getUserDataPath: () => ud,
    isPortInUse: () => Promise.resolve(false),
    isPackaged: () => false,
    repoRoot: repo,
    ...extra,
  });
  return { sb, settings, ud };
}

test('resolveImage: the four precedence cases, literal', () => {
  // 1. An image override wins over everything, ref included.
  assert.deepStrictEqual(
    resolveImage({ isPackaged: true, appVersion: '9.9.9', override: 'my/img:tag', repoRoot: '/repo', ref: 'master', srcDir: '/ud/sandbox/src', sha: 'abc1234' }),
    { kind: 'image', image: 'my/img:tag' },
  );
  // 2. A ref beats the packaged GHCR tag — a packaged app CAN build from a
  //    worktree, because docker does the build, not the app.
  assert.deepStrictEqual(
    resolveImage({ isPackaged: true, appVersion: '9.9.9', override: null, repoRoot: '/repo', ref: 'master', srcDir: '/ud/sandbox/src', sha: 'abc1234' }),
    { kind: 'build', context: '/ud/sandbox/src', dockerfile: 'docker/web/Dockerfile', ref: 'master', sha: 'abc1234' },
  );
  // 2b. …and beats the dev checkout too, so the two halves agree.
  assert.deepStrictEqual(
    resolveImage({ isPackaged: false, appVersion: '9.9.9', override: null, repoRoot: '/repo', ref: 'master', srcDir: '/ud/sandbox/src', sha: null }),
    { kind: 'build', context: '/ud/sandbox/src', dockerfile: 'docker/web/Dockerfile', ref: 'master', sha: null },
  );
  // 3. No ref, packaged → the version tag.
  assert.deepStrictEqual(
    resolveImage({ isPackaged: true, appVersion: '9.9.9', override: null, repoRoot: '/repo', ref: null, srcDir: null, sha: null }),
    { kind: 'image', image: 'ghcr.io/avirtual/clodex:9.9.9' },
  );
  // 4. No ref, dev → the live checkout, WITHOUT ref/sha keys.
  assert.deepStrictEqual(
    resolveImage({ isPackaged: false, appVersion: '9.9.9', override: null, repoRoot: '/repo', ref: null, srcDir: null, sha: null }),
    { kind: 'build', context: '/repo', dockerfile: 'docker/web/Dockerfile' },
  );
});

test('setConfig: DEFAULT_CONFIG carries ref:null and a plain branch name is accepted', () => {
  assert.strictEqual(DEFAULT_CONFIG.ref, null);
  const { sb } = refSandbox(tempRepo());
  assert.strictEqual(sb.getConfig().ref, null);
  assert.strictEqual(sb.setConfig({ ref: '  feature/x  ' }).ref, 'feature/x');
  assert.strictEqual(sb.setConfig({ ref: '' }).ref, null, 'an empty string clears the ref');
  sb.setConfig({ ref: 'master' });
  assert.strictEqual(sb.setConfig({ ref: null }).ref, null, 'null clears the ref');
});

test("setConfig: rejects a traversal ref and an over-long one, each with a reason", () => {
  const { sb } = refSandbox(tempRepo());
  const traversal = sb.setConfig({ ref: '../x' });
  assert.strictEqual(traversal.ok, false);
  assert.match(traversal.error, /\.\./);
  const long = sb.setConfig({ ref: 'a'.repeat(200) });
  assert.strictEqual(long.ok, false);
  assert.match(long.error, /too long/i);
  // A rejected save must not have PERSISTED anything — the reason is the whole
  // point, and a box left half-configured would build from a ref nobody typed.
  assert.strictEqual(sb.getConfig().ref, null);
});

test('up: with a ref, src is a detached worktree at that commit and compose builds from it', async () => {
  const repo = tempRepo('one');
  const sha = gitIn(repo, ['rev-parse', 'HEAD']);
  const { sb } = refSandbox(repo);
  sb.setConfig({ ref: 'master' });

  const r = await sb.up();
  assert.strictEqual(r.ok, true, r.error);
  assert.strictEqual(gitIn(sb.srcDir(), ['rev-parse', 'HEAD']), sha);
  assert.strictEqual(gitIn(sb.srcDir(), ['rev-parse', '--abbrev-ref', 'HEAD']), 'HEAD', 'detached, so the ref stays free for the operator');
  assert.strictEqual(fs.readFileSync(path.join(sb.srcDir(), 'marker.txt'), 'utf8'), 'one');

  const yaml = fs.readFileSync(sb.composePath(), 'utf8');
  assert.match(yaml, new RegExp(`context: ${sb.srcDir().replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`, 'm'));
  assert.ok(!yaml.includes(`context: ${repo}\n`), 'the live checkout is NOT the build context');

  await removeWorktree(sb.srcDir());
});

test('up: a second up after a new commit on the ref moves src forward', async () => {
  const repo = tempRepo('one');
  const { sb } = refSandbox(repo);
  sb.setConfig({ ref: 'master' });
  assert.strictEqual((await sb.up()).ok, true);
  assert.strictEqual(fs.readFileSync(path.join(sb.srcDir(), 'marker.txt'), 'utf8'), 'one');

  const second = commitOn(repo, 'master', 'two');
  assert.strictEqual((await sb.up()).ok, true);
  assert.strictEqual(gitIn(sb.srcDir(), ['rev-parse', 'HEAD']), second);
  assert.strictEqual(fs.readFileSync(path.join(sb.srcDir(), 'marker.txt'), 'utf8'), 'two');

  await removeWorktree(sb.srcDir());
});

test('rebuild: refreshes src to the ref before building it', async () => {
  const repo = tempRepo('one');
  const { sb } = refSandbox(repo);
  sb.setConfig({ ref: 'master' });
  assert.strictEqual((await sb.up()).ok, true);
  const second = commitOn(repo, 'master', 'two');
  assert.strictEqual((await sb.rebuild()).ok, true);
  assert.strictEqual(gitIn(sb.srcDir(), ['rev-parse', 'HEAD']), second);
  await removeWorktree(sb.srcDir());
});

test('up: an unresolvable ref fails with the exact error and leaves src untouched', async () => {
  const repo = tempRepo('one');
  const first = gitIn(repo, ['rev-parse', 'HEAD']);
  const { sb } = refSandbox(repo);
  sb.setConfig({ ref: 'master' });
  assert.strictEqual((await sb.up()).ok, true);

  sb.setConfig({ ref: 'no-such-branch' });
  const r = await sb.up();
  assert.strictEqual(r.ok, false);
  assert.strictEqual(r.error, `ref no-such-branch does not resolve in ${repo}`);
  // The PREVIOUS build context survives: a failed refresh must not leave the box
  // with nothing to build from.
  assert.strictEqual(gitIn(sb.srcDir(), ['rev-parse', 'HEAD']), first);

  await removeWorktree(sb.srcDir());
});

test('up: a ref on a repoRoot that is not a git checkout says so, and does not fall back', async () => {
  const notARepo = fs.mkdtempSync(path.join(TMP_USERDATA, 'asar-'));
  const { sb } = refSandbox(notARepo, { isPackaged: () => true, appVersion: '9.9.9' });
  sb.setConfig({ ref: 'master' });
  const r = await sb.up();
  assert.strictEqual(r.ok, false);
  assert.strictEqual(r.error, 'this Clodex was not launched from a git checkout; tracking a ref needs one');
  assert.ok(!fs.existsSync(sb.composePath()), 'no compose was written, so nothing silently built the GHCR tag');
});

test('status: reports the tracked ref and the sha src is parked on', async () => {
  const repo = tempRepo('one');
  const sha = gitIn(repo, ['rev-parse', 'HEAD']);
  const { sb } = refSandbox(repo);

  const before = await sb.status();
  assert.strictEqual(before.ref, null);
  assert.strictEqual(before.sha, null, 'no ref tracked → no sha to report');

  sb.setConfig({ ref: 'master' });
  assert.strictEqual((await sb.up()).ok, true);
  const after = await sb.status();
  assert.strictEqual(after.ref, 'master');
  assert.strictEqual(after.sha, sha);

  await removeWorktree(sb.srcDir());
});

// t808 rider: bringUp only checks out a ref when `image` is unset (the
// `config.ref && !config.image` gate), so with an override in place srcDir is
// parked on whatever ref was last synced — some EARLIER one, or none. status()
// reporting that stale pair is how a box advertises a ref it is demonstrably not
// running, which is the read a team's seats would trust.
test('status: an image override suppresses ref/sha — the box is not built from the ref', async () => {
  const repo = tempRepo('one');
  const sha = gitIn(repo, ['rev-parse', 'HEAD']);
  const { sb } = refSandbox(repo);

  sb.setConfig({ ref: 'master' });
  assert.strictEqual((await sb.up()).ok, true);
  const tracked = await sb.status();
  assert.strictEqual(tracked.ref, 'master');
  assert.strictEqual(tracked.sha, sha, 'the ref really was checked out — the src worktree is on disk');

  // The ref STAYS in config; only the override is added. src is untouched, so a
  // status that still read it would return the same sha as above.
  sb.setConfig({ image: 'my/img:tag' });
  const overridden = await sb.status();
  assert.strictEqual(overridden.ref, null);
  assert.strictEqual(overridden.sha, null);
  assert.strictEqual(sb.getConfig().ref, 'master', 'the tracked ref is suppressed in the report, not erased');

  await removeWorktree(sb.srcDir());
});

test('manager: remove() removes the box src worktree, not just the registry row', async () => {
  const repo = tempRepo('one');
  const settings = fakeBoxSettings([{ id: 'proj', label: 'proj', config: { ref: 'master' } }]);
  const ud = freshUserData();
  const mgr = createSandboxManager({ registryDir: TMP_REGISTRY,
    spawn: okComposeSpawn(),
    getUiSettings: () => settings,
    getUserDataPath: () => ud,
    isPortInUse: () => Promise.resolve(false),
    isPackaged: () => false,
    repoRoot: repo,
  });
  const box = mgr.get('proj');
  assert.strictEqual((await box.up()).ok, true);
  // git prints realpath'd paths and the temp userData sits under a symlinked
  // /tmp, so the raw srcDir would never appear in the listing either way.
  const src = fs.realpathSync(box.srcDir());
  assert.ok(gitIn(repo, ['worktree', 'list']).includes(src), 'git knows the src worktree before remove');

  const r = await mgr.remove('proj');
  assert.strictEqual(r.ok, true);
  assert.ok(!gitIn(repo, ['worktree', 'list']).includes(src), 'git no longer names the src worktree');
  assert.deepStrictEqual(settings._state().boxes, []);
});

// The git calls belong in git-worktree.js, where every other one in this repo
// lives: a second, sandbox-local way to shell out to git would drift from the
// error handling and the main-tree guard that file already carries.
test('source shape: sandbox.js shells out to git nowhere — the calls live in git-worktree.js', () => {
  const src = fs.readFileSync(path.join(__dirname, '..', 'sandbox.js'), 'utf8');
  assert.ok(!src.includes("spawnSync('git'"), 'no spawnSync of git');
  assert.ok(!/['"`]git['"`]/.test(src), 'no bare git literal — that is git-worktree.js\'s job');
});
