'use strict';

// The bash half of "a real shell, not a fake". term-shim.test.js pins the
// generated BYTES, which is all a fake fs can see; nothing there can say
// whether bash does what those bytes intend — and the two questions fail
// differently. A hook that is subtly wrong about bash produces a file that
// looks right in every string assertion and reports nothing, or worse, prints
// itself onto the operator's prompt.
//
// That is the same lesson as the `^U^K` defect (see term-exec-keymap.test.js):
// a recorder fake agrees with whatever bytes we chose. It is also how the
// stray-SOH/STX defect this file pins was found — `\[ \]` reads as correct in
// any source review and is only wrong when a shell expands it.
//
// So this drives the SHIPPING modules — buildTermShim, createDrawerPtys,
// createMarkParser, wired as engine.js wires them — against a real bash, and
// asks what the agent would actually have been told.

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const { buildTermShim, bashSupport } = require('../term-shim');
const { createDrawerPtys } = require('../drawer-pty');
const { createMarkParser } = require('../term-marks');

// A bash too old for PS0 cannot be shimmed at all, so it is not a machine this
// property can be measured on. Resolved through bashSupport rather than a
// version parse of our own: a second copy of the floor is how a supported shell
// starts being told it is unsupported.
const CANDIDATES = ['/opt/homebrew/bin/bash', '/usr/local/bin/bash', '/bin/bash'];
const BASH = CANDIDATES.find((p) => {
  try {
    if (!fs.statSync(p).isFile()) return false;
  } catch { return false; }
  return bashSupport({ shell: p }).ok;
}) || null;

let pty = null;
try { pty = require('node-pty'); } catch {}

const SKIP = !pty ? 'node-pty unavailable'
  : !BASH ? 'no bash new enough for PS0 (needs 4.4+; macOS ships 3.2)'
    : false;

// Every wait polls for CONTENT and returns as soon as it appears, so a passing
// run costs the real latency and never this — it is a deadline on how long a
// FAILING case takes to give up. Sized like the keymap test's, for the same
// reason: a shell competing with the rest of the suite needs longer to reach
// its first prompt than one running alone.
const SETTLE_MS = 20000;

function waitFor(pred, ms = SETTLE_MS) {
  return new Promise((resolve) => {
    const end = Date.now() + ms;
    const tick = () => {
      if (pred()) return resolve(true);
      if (Date.now() > end) return resolve(false);
      setTimeout(tick, 40);
    };
    tick();
  });
}

// One shimmed bash, wired the way engine.js wires the real thing.
//
// HOME is redirected to a scratch dir, which is what makes this hermetic: the
// generated rc sources the operator's own profile by design, so against a real
// $HOME these tests would measure whatever the developer happens to have in
// theirs. `profile` writes a ~/.bash_profile into that scratch home — the same
// door a real operator's startup comes through, which is why it is written
// there rather than appended to the generated file. Appending would put their
// hook AFTER ours and test an ordering that cannot happen.
async function withShell(run, { profile, env: envOver } = {}) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'clodex-bash-marks-'));
  const home = path.join(dir, 'home');
  fs.mkdirSync(home, { recursive: true });
  if (profile) fs.writeFileSync(path.join(home, '.bash_profile'), profile);
  const shimDir = path.join(dir, 'shim');
  const results = [];
  const passive = [];
  let proc = null;
  let raw = '';

  const ptys = createDrawerPtys({
    spawn: (file, args, opts) => {
      proc = pty.spawn(file, args, opts);
      proc.onData((d) => { raw += d; });
      return proc;
    },
    send: () => {},
    shell: BASH,
    cwdFor: () => dir,
    // A private HISTFILE: the dedup guard reads `history`, and inheriting the
    // developer's own history file would make what this test measures depend on
    // what they last typed.
    env: { ...process.env, HOME: home, HISTFILE: path.join(dir, 'hist'), ...(envOver || {}) },
    shimEnv: () => buildTermShim({ dir: shimDir, shell: BASH }),
    makeMarkParser: createMarkParser,
    onCommand: (seat, rec) => passive.push(rec),
    onExecResult: (seat, res) => results.push(res),
    log: { info() {}, warn() {}, error() {} },
  });

  try {
    const sp = ptys.spawn('w', 'seat', { cols: 80, rows: 24 });
    assert.strictEqual(sp.ok, true, `the shell spawned: ${sp.error || ''}`);
    // ENTER: a shell that was NOT shimmed refuses every exec with `no-marks`,
    // and every assertion below would then be measuring the refusal rather
    // than the hooks.
    assert.strictEqual(ptys._execState('w', 'seat').shimmed, true,
      'ENTER: the shell was born shimmed');
    // The first prompt has been drawn once a D/A pair has arrived. Waiting on
    // the marks rather than a timer: exec() refuses while the parser thinks a
    // command is open, and a fixed sleep would be a guess about machine load.
    const ready = await waitFor(() => /\x1b\]133;A\x07/.test(raw));
    assert.ok(ready, `the shell reached its first prompt\n--- raw ---\n${raw}`);

    // One command through the real exec path, answered through onExecResult.
    const exec = async (command) => {
      const before = results.length;
      const r = ptys.exec('w', 'seat', command);
      assert.strictEqual(r.ok, true, `exec accepted \`${command}\`: ${r.code || ''} ${r.error || ''}`);
      const got = await waitFor(() => results.length > before);
      assert.ok(got, `\`${command}\` was answered\n--- raw ---\n${raw}`);
      return results[results.length - 1];
    };

    return await run({ exec, ptys, results, passive, dir, raw: () => raw, proc: () => proc });
  } finally {
    try { ptys.dispose(); } catch {}
    try { if (proc) proc.kill(); } catch {}
    try { fs.rmSync(dir, { recursive: true, force: true }); } catch {}
  }
}

const opts = { skip: SKIP, timeout: 120000 };

test('a real bash reports a command, its text and its exit code', opts, async () => {
  await withShell(async ({ exec }) => {
    const res = await exec('echo hello');
    assert.strictEqual(res.status, 'ok', `the command completed: ${JSON.stringify(res)}`);
    assert.strictEqual(res.record.command, 'echo hello', 'the reported line is what ran');
    assert.strictEqual(res.record.exitCode, 0);
    assert.match(res.record.output, /hello/, 'the output was captured');
  });
});

// The `${(q)}` class of bug, which is what made zsh's quoting operator
// unusable: a reported command that is subtly re-escaped is wrong on every
// command, and nothing but a real shell shows it.
test('a command with spaces and quotes round-trips EXACTLY', opts, async () => {
  await withShell(async ({ exec }) => {
    const cmd = `echo 'sp  ace "q" *'`;
    const res = await exec(cmd);
    assert.strictEqual(res.record.command, cmd,
      'the reported command must be byte-identical to what was typed');
  });
});

test('a non-zero exit arrives as that exact code', opts, async () => {
  await withShell(async ({ exec }) => {
    const res = await exec('sh -c "exit 7"');
    assert.strictEqual(res.record.exitCode, 7, 'not 0, not 1, not null');
  });
});

// The DEBUG trap's failure mode, and the reason PS0 was chosen over it: a trap
// fires per SIMPLE command, so `a; b` would mark twice and the second mark
// would open a command the agent never sent.
test('a compound command reports ONCE, not once per simple command', opts, async () => {
  await withShell(async ({ exec, results, passive }) => {
    const res = await exec('echo a; echo b');
    assert.strictEqual(res.record.command, 'echo a; echo b', 'ENTER: the whole line was reported');
    assert.strictEqual(res.record.exitCode, 0);
    // Give a second, spurious mark time to arrive before declaring there wasn't
    // one — asserting an absence immediately after the first answer would pass
    // on a shell that simply had not sent it yet.
    await new Promise((r) => setTimeout(r, 1500));
    assert.strictEqual(results.length, 1, `exactly one answer, got ${JSON.stringify(results)}`);
    assert.strictEqual(passive.length, 0, 'and our own command is not also reported passively');
  });
});

// Measured defect: `\[ \]` is a readline hint that only PS1 gets stripped of.
// In PS0 bash expands it to literal SOH/STX and sends it to the terminal, where
// it landed at the head of every captured command's output — bytes the agent
// would have been shown as part of the result.
test('no stray SOH/STX bytes leak into the captured output', opts, async () => {
  await withShell(async ({ exec, raw }) => {
    const res = await exec('echo clean');
    assert.match(res.record.output, /clean/, 'ENTER: output really was captured');
    assert.ok(!/[\x01\x02]/.test(res.record.output),
      `PS0 leaked a readline hint into the output: ${JSON.stringify(res.record.output)}`);
    // The stream itself, not just the captured slice: a mark parser that
    // happened to swallow the bytes would hide them from the assertion above
    // while the operator still saw them on screen.
    assert.ok(!/[\x01\x02]/.test(raw()),
      'the operator\'s terminal must not receive them either');
  });
});

// The operator's shell must behave exactly as it does without us. Their
// PROMPT_COMMAND is prepended to, never replaced — and ours running FIRST is
// what keeps `$?` trustworthy, so this also pins that the prepend survived
// contact with a real shell.
test("an operator's own PROMPT_COMMAND still runs, and ours runs first", opts, async () => {
  const marker = path.join(os.tmpdir(), `clodex-pc-${process.pid}-${Date.now()}`);
  try {
    await withShell(async ({ exec }) => {
      // Their hook leads with `true`, which destroys `$?` for anything after
      // it. Reporting 3 is only possible if ours ran first.
      const res = await exec('sh -c "exit 3"');
      assert.strictEqual(res.record.exitCode, 3,
        'ours ran before theirs — appending would have reported 0');
      assert.ok(fs.existsSync(marker), 'their PROMPT_COMMAND still ran');
    }, { profile: `PROMPT_COMMAND='true; echo ran >> ${marker}'\n` });
  } finally {
    try { fs.rmSync(marker, { force: true }); } catch {}
  }
});

// Their profile is what the reconstruction exists to run. Asserted separately
// from the PROMPT_COMMAND case above because that one would still pass if the
// profile were sourced and its hook then clobbered.
test("the operator's own .bash_profile is sourced", opts, async () => {
  await withShell(async ({ exec }) => {
    const res = await exec('echo "[$CLODEX_PROFILE_RAN]"');
    assert.match(res.record.output, /\[yes\]/,
      'dropping -l must not cost the operator their own startup');
  }, { profile: 'export CLODEX_PROFILE_RAN=yes\n' });
});

// A command the OPERATOR types is the passive-reporting path, which is a
// different consumer from exec's answer and could be broken while exec works.
test('a command typed by the operator is reported passively', opts, async () => {
  await withShell(async ({ passive, proc }) => {
    proc().write('echo typed_by_operator\r');
    const got = await waitFor(() => passive.length > 0);
    assert.ok(got, 'the operator\'s own command was reported');
    assert.strictEqual(passive[passive.length - 1].command, 'echo typed_by_operator');
    assert.strictEqual(passive[passive.length - 1].exitCode, 0);
  });
});

// Dropping -l is what makes --rcfile work at all, and the generated rc puts the
// login startup back. Both halves are asserted: the reconstruction happened,
// and the known gap is REPORTED honestly rather than faked.
test('the reconstructed shell has login PATH but answers login_shell false', opts, async () => {
  await withShell(async ({ exec }) => {
    const res = await exec('shopt -q login_shell && echo LOGIN=yes || echo LOGIN=no');
    assert.match(res.record.output, /LOGIN=no/,
      'a reconstructed shell is NOT a login shell, and faking the flag would be worse');
  });
});

// /etc/profile is where the distro PATH comes from, and skipping it would gut
// the reason the tab spawned a login shell at all.
//
// The shell is given a DELIBERATELY BROKEN PATH to start from, because the
// obvious assertion — "/usr/bin is on PATH" — is true of a shell that inherited
// it from this process and never read /etc/profile at all. Mutation-checked:
// with the source removed, the inherited-PATH version still passed.
test('/etc/profile is really sourced, not merely named', opts, async () => {
  await withShell(async ({ exec }) => {
    const res = await exec('case ":$PATH:" in *:/usr/bin:*) echo HAS=yes;; *) echo HAS=no;; esac');
    assert.match(res.record.output, /HAS=(yes|no)/, 'ENTER: the probe ran and answered');
    assert.match(res.record.output, /HAS=yes/,
      'PATH started as /nonexistent, so only /etc/profile could have put /usr/bin back');
  }, { env: { PATH: '/nonexistent' } });
});

// A machine with no usable bash would otherwise report a green file that
// measured nothing at all. Not skipped: the ABSENCE of a shell is a fact worth
// stating in the run, and CI on a box with only bash 3.2 should say so out loud
// rather than quietly pass.
test('the bash reporting property was measured against a real shell', () => {
  assert.ok(pty, 'node-pty is required for this file to mean anything');
  assert.ok(BASH, `no bash >= ${'4.4'} found in ${CANDIDATES.join(', ')} — nothing here was measured`);
});
