'use strict';

// The bash half of "a real shell, not a fake". term-shim.test.js pins the
// generated BYTES, which is all a fake fs can see; nothing there can say
// whether bash does what those bytes intend — and the two questions fail
// differently. A hook that is subtly wrong about bash produces a file that
// looks right in every string assertion and reports nothing, or worse, prints
// itself onto the operator's prompt.
//
// That is the same lesson as the `^U^K` defect (see term-exec-keymap.test.js):
// a recorder fake agrees with whatever bytes we chose. It is also how the
// stray-SOH/STX defect this file pins was found — `\[ \]` reads as correct in
// any source review and is only wrong when a shell expands it.
//
// So this drives the SHIPPING modules — buildTermShim, createDrawerPtys,
// createMarkParser, wired as engine.js wires them — against a real bash, and
// asks what the agent would actually have been told.

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const { buildTermShim, bashSupport } = require('../term-shim');
const { createDrawerPtys } = require('../drawer-pty');
const { createMarkParser, formatCommand } = require('../term-marks');
const { pidAlive, reapPty } = require('./lib/pty-reap');

// A bash too old for PS0 cannot be shimmed at all, so it is not a machine this
// property can be measured on. Resolved through bashSupport rather than a
// version parse of our own: a second copy of the floor is how a supported shell
// starts being told it is unsupported.
const CANDIDATES = ['/opt/homebrew/bin/bash', '/usr/local/bin/bash', '/bin/bash'];
const BASH = CANDIDATES.find((p) => {
  try {
    if (!fs.statSync(p).isFile()) return false;
  } catch { return false; }
  return bashSupport({ shell: p }).ok;
}) || null;

let pty = null;
try { pty = require('node-pty'); } catch {}

const SKIP = !pty ? 'node-pty unavailable'
  : !BASH ? 'no bash new enough for PS0 (needs 4.4+; macOS ships 3.2)'
    : false;

// Every wait polls for CONTENT and returns as soon as it appears, so a passing
// run costs the real latency and never this — it is a deadline on how long a
// FAILING case takes to give up. Sized like the keymap test's, for the same
// reason: a shell competing with the rest of the suite needs longer to reach
// its first prompt than one running alone.
const SETTLE_MS = 20000;

function waitFor(pred, ms = SETTLE_MS) {
  return new Promise((resolve) => {
    const end = Date.now() + ms;
    const tick = () => {
      if (pred()) return resolve(true);
      if (Date.now() > end) return resolve(false);
      setTimeout(tick, 40);
    };
    tick();
  });
}

// One shimmed bash, wired the way engine.js wires the real thing.
//
// HOME is redirected to a scratch dir, which is what makes this hermetic: the
// generated rc sources the operator's own profile by design, so against a real
// $HOME these tests would measure whatever the developer happens to have in
// theirs. `profile` writes a ~/.bash_profile into that scratch home — the same
// door a real operator's startup comes through, which is why it is written
// there rather than appended to the generated file. Appending would put their
// hook AFTER ours and test an ordering that cannot happen.
async function withShell(run, { profile, env: envOver } = {}) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'clodex-bash-marks-'));
  const home = path.join(dir, 'home');
  fs.mkdirSync(home, { recursive: true });
  if (profile) fs.writeFileSync(path.join(home, '.bash_profile'), profile);
  const shimDir = path.join(dir, 'shim');
  const results = [];
  const passive = [];
  let proc = null;
  let raw = '';

  const ptys = createDrawerPtys({
    spawn: (file, args, opts) => {
      proc = pty.spawn(file, args, opts);
      proc.onData((d) => { raw += d; });
      return proc;
    },
    send: () => {},
    shell: BASH,
    cwdFor: () => dir,
    // A private HISTFILE: the dedup guard reads `history`, and inheriting the
    // developer's own history file would make what this test measures depend on
    // what they last typed.
    env: { ...process.env, HOME: home, HISTFILE: path.join(dir, 'hist'), ...(envOver || {}) },
    shimEnv: () => buildTermShim({ dir: shimDir, shell: BASH }),
    makeMarkParser: createMarkParser,
    onCommand: (seat, rec) => passive.push(rec),
    onExecResult: (seat, res) => results.push(res),
    log: { info() {}, warn() {}, error() {} },
  });

  try {
    const sp = ptys.spawn('w', 'seat', { cols: 80, rows: 24 });
    assert.strictEqual(sp.ok, true, `the shell spawned: ${sp.error || ''}`);
    // ENTER: a shell that was NOT shimmed refuses every exec with `no-marks`,
    // and every assertion below would then be measuring the refusal rather
    // than the hooks.
    assert.strictEqual(ptys._execState('w', 'seat').shimmed, true,
      'ENTER: the shell was born shimmed');
    // The first prompt has been drawn once a D/A pair has arrived. Waiting on
    // the marks rather than a timer: exec() refuses while the parser thinks a
    // command is open, and a fixed sleep would be a guess about machine load.
    const ready = await waitFor(() => /\x1b\]133;A\x07/.test(raw));
    assert.ok(ready, `the shell reached its first prompt\n--- raw ---\n${raw}`);

    // One command through the real exec path, answered through onExecResult.
    const exec = async (command) => {
      const before = results.length;
      const r = ptys.exec('w', 'seat', command);
      assert.strictEqual(r.ok, true, `exec accepted \`${command}\`: ${r.code || ''} ${r.error || ''}`);
      const got = await waitFor(() => results.length > before);
      assert.ok(got, `\`${command}\` was answered\n--- raw ---\n${raw}`);
      return results[results.length - 1];
    };

    return await run({ exec, ptys, results, passive, dir, raw: () => raw, proc: () => proc });
  } finally {
    try { ptys.dispose(); } catch {}
    // See the sibling call site in term-exec-keymap.test.js: the boolean is the
    // only witness to a pid that outlived SIGKILL and is wedging the runner.
    try { if (!(await reapPty(proc))) console.error(`reapPty: pid ${proc && proc.pid} survived SIGKILL`); } catch {}
    try { fs.rmSync(dir, { recursive: true, force: true }); } catch {}
  }
}

const opts = { skip: SKIP, timeout: 120000 };

// An exit-code assertion can be answering a question nobody asked. exec() writes
// ^C and the command as two writes, and bash discards pending input when SIGINT
// lands, so under load the command's leading bytes go with it — the truncated
// remainder still RUNS and still reports. Measured here at 32 concurrent runs of
// this file: `sh -c "exit 7"` arrived as `h -c "exit 7"` and answered 127, with
// PATH verifiably intact and `command -v sh` answering /bin/sh in the same shell.
// It is the swallowed-byte race drawer-pty.js exec() documents against its own
// two writes (measured there as `cho: command not found`), not an environment
// failure and not the shell failing to start.
//
// Same reasoning, and the same SHORTER-THAN test, as the compound-command subject
// below — see its comment for why length beats endsWith and why an empty
// (deliberately unnamed) record must fall through to be judged by the real
// assertion. Kept as a shared helper because the cost it prevents is specific:
// reading a corrupted write as a defect in the property under test is what cost
// t418 a false rejection, and a 127 landing on the PROMPT_COMMAND subject accuses
// an ordering regression that reports 0 when it genuinely happens, never 127.
function assertRanIntact(res, typed, expected, message) {
  const got = res.record && res.record.command;
  if (got && got.length < typed.length) {
    assert.fail('the command was CORRUPTED in transit — the shell received '
      + `${JSON.stringify(got)}, shorter than the ${JSON.stringify(typed)} that was typed, `
      + `and ran that instead (exit ${res.record.exitCode}, output ${JSON.stringify((res.record.output || '').trim())}). `
      + 'That is the swallowed-byte race in drawer-pty.js exec(), a LOAD failure of the '
      + `two-write abandon handshake — NOT a defect in what this test asserts (${message}).`);
  }
  assert.strictEqual(res.record.exitCode, expected, message);
}

test('a real bash reports a command, its text and its exit code', opts, async () => {
  await withShell(async ({ exec }) => {
    const res = await exec('echo hello');
    assert.strictEqual(res.status, 'ok', `the command completed: ${JSON.stringify(res)}`);
    assert.strictEqual(res.record.command, 'echo hello', 'the reported line is what ran');
    assert.strictEqual(res.record.exitCode, 0);
    assert.match(res.record.output, /hello/, 'the output was captured');
  });
});

// The `${(q)}` class of bug, which is what made zsh's quoting operator
// unusable: a reported command that is subtly re-escaped is wrong on every
// command, and nothing but a real shell shows it.
test('a command with spaces and quotes round-trips EXACTLY', opts, async () => {
  await withShell(async ({ exec }) => {
    const cmd = `echo 'sp  ace "q" *'`;
    const res = await exec(cmd);
    assert.strictEqual(res.record.command, cmd,
      'the reported command must be byte-identical to what was typed');
  });
});

test('a non-zero exit arrives as that exact code', opts, async () => {
  await withShell(async ({ exec }) => {
    const res = await exec('sh -c "exit 7"');
    assertRanIntact(res, 'sh -c "exit 7"', 7, 'not 0, not 1, not null');
  });
});

// The DEBUG trap's failure mode, and the reason PS0 was chosen over it: a trap
// fires per SIMPLE command, so `a; b` would mark twice and the second mark
// would open a command the agent never sent.
test('a compound command reports ONCE, not once per simple command', opts, async () => {
  await withShell(async ({ exec, results, passive, raw }) => {
    const res = await exec('echo a; echo b');
    // A swallowed first byte reports `cho a; echo b` here — a real command that
    // RAN, so the count assertions below are all satisfied and only the text
    // gives it away. Named separately from the reporting property this test
    // exists for: the two failures have different causes and different owners,
    // and reading a corrupted write as "the shim reported the wrong line" is
    // what cost t418 a false rejection.
    // SHORTER-THAN, not endsWith. `endsWith('')` is true of every string, so an
    // UNNAMED record — the HISTCONTROL/HISTIGNORE family this file documents
    // below, where the payload is deliberately empty — would have been reported
    // as a corrupted write. It also catches a loss from the MIDDLE of the
    // command (`echo a; eho b`), which endsWith misses entirely and which is the
    // other shape drawer-pty's quiet window exists for. Empty is falsy, so an
    // unnamed record falls through to the strictEqual below and is judged there.
    const typed = 'echo a; echo b';
    if (res.record.command && res.record.command.length < typed.length) {
      assert.fail(`the write was CORRUPTED in transit — the shell received `
        + `${JSON.stringify(res.record.command)}, shorter than what was typed. `
        + `That is the swallowed-byte race in exec(), not a reporting defect`
        + `\n--- raw ---\n${raw()}`);
    }
    assert.strictEqual(res.record.command, 'echo a; echo b', 'ENTER: the whole line was reported');
    assert.strictEqual(res.record.exitCode, 0);
    // Give a second, spurious mark time to arrive before declaring there wasn't
    // one — asserting an absence immediately after the first answer would pass
    // on a shell that simply had not sent it yet.
    await new Promise((r) => setTimeout(r, 1500));
    assert.strictEqual(results.length, 1, `exactly one answer, got ${JSON.stringify(results)}`);
    assert.strictEqual(passive.length, 0, 'and our own command is not also reported passively');
  });
});

// Measured defect: `\[ \]` is a readline hint that only PS1 gets stripped of.
// In PS0 bash expands it to literal SOH/STX and sends it to the terminal, where
// it landed at the head of every captured command's output — bytes the agent
// would have been shown as part of the result.
test('no stray SOH/STX bytes leak into the captured output', opts, async () => {
  await withShell(async ({ exec, raw }) => {
    const res = await exec('echo clean');
    assert.match(res.record.output, /clean/, 'ENTER: output really was captured');
    assert.ok(!/[\x01\x02]/.test(res.record.output),
      `PS0 leaked a readline hint into the output: ${JSON.stringify(res.record.output)}`);
    // The stream itself, not just the captured slice: a mark parser that
    // happened to swallow the bytes would hide them from the assertion above
    // while the operator still saw them on screen.
    assert.ok(!/[\x01\x02]/.test(raw()),
      'the operator\'s terminal must not receive them either');
  });
});

// The operator's shell must behave exactly as it does without us. Their
// PROMPT_COMMAND is prepended to, never replaced — and ours running FIRST is
// what keeps `$?` trustworthy, so this also pins that the prepend survived
// contact with a real shell.
test("an operator's own PROMPT_COMMAND still runs, and ours runs first", opts, async () => {
  const marker = path.join(os.tmpdir(), `clodex-pc-${process.pid}-${Date.now()}`);
  try {
    await withShell(async ({ exec }) => {
      // Their hook leads with `true`, which destroys `$?` for anything after
      // it. Reporting 3 is only possible if ours ran first.
      const res = await exec('sh -c "exit 3"');
      assertRanIntact(res, 'sh -c "exit 3"', 3,
        'ours ran before theirs — appending would have reported 0');
      assert.ok(fs.existsSync(marker), 'their PROMPT_COMMAND still ran');
    }, { profile: `PROMPT_COMMAND='true; echo ran >> ${marker}'\n` });
  } finally {
    try { fs.rmSync(marker, { force: true }); } catch {}
  }
});

// Their profile is what the reconstruction exists to run. Asserted separately
// from the PROMPT_COMMAND case above because that one would still pass if the
// profile were sourced and its hook then clobbered.
test("the operator's own .bash_profile is sourced", opts, async () => {
  await withShell(async ({ exec }) => {
    const res = await exec('echo "[$CLODEX_PROFILE_RAN]"');
    assert.match(res.record.output, /\[yes\]/,
      'dropping -l must not cost the operator their own startup');
  }, { profile: 'export CLODEX_PROFILE_RAN=yes\n' });
});

// A command the OPERATOR types is the passive-reporting path, which is a
// different consumer from exec's answer and could be broken while exec works.
test('a command typed by the operator is reported passively', opts, async () => {
  await withShell(async ({ passive, proc }) => {
    proc().write('echo typed_by_operator\r');
    const got = await waitFor(() => passive.length > 0);
    assert.ok(got, 'the operator\'s own command was reported');
    assert.strictEqual(passive[passive.length - 1].command, 'echo typed_by_operator');
    assert.strictEqual(passive[passive.length - 1].exitCode, 0);
  });
});

// AN OPERATOR PROFILE RUNNING `set -u` MAKES EVERY BARE EXPANSION IN THE HOOK
// FATAL, and the failure is silent in the worst way: the abort happens before
// __clodex_preexec's printf, so no C mark is emitted, no command is ever framed,
// and every exec ends timeout -> lost rather than refusing. `set -u` is common
// enough in a careful operator's profile to be worth the shell this costs.
//
// The passive path is the observation point rather than exec's: exec would prove
// the same thing by waiting out its 120s timeout, and a test that measures a
// deadline is a test that costs one on every green run.
test("an operator's `set -u` does not silence the marks", opts, async () => {
  await withShell(async ({ passive, proc }) => {
    proc().write('echo strict_mode\r');
    const got = await waitFor(() => passive.length > 0);
    assert.ok(got, 'a bare ${HISTCONTROL}, ${HISTIGNORE} or ${PS0} here emits no mark at all');
    assert.strictEqual(passive[passive.length - 1].command, 'echo strict_mode',
      'and the command is still named');
  }, { profile: 'set -u\n' });
});

// THE v5.1.x DEFECT, and it is a real shell's behaviour rather than ours: a
// command bash declines to add to history leaves the history NUMBER unchanged,
// and the guard read that as "we do not know what ran". Reproduced in
// ghcr.io/avirtual/clodex:5.1.1, where ubuntu's stock ~/.bashrc sets
// HISTCONTROL=ignoreboth — so every REPEATED command arrived unnamed and the
// agent was told "the shell did not report which command ran".
//
// Set through the PROFILE rather than the env, because that is the door it comes
// through on a real box: the generated rc sources their startup, which is where
// a distro puts this.
test('a REPEATED command is still named under HISTCONTROL=ignoredups', opts, async () => {
  await withShell(async ({ exec }) => {
    const first = await exec('echo twice');
    assert.strictEqual(first.record.command, 'echo twice', 'ENTER: the first one was named');
    const second = await exec('echo twice');
    assert.strictEqual(second.record.command, 'echo twice',
      'the entry was suppressed BECAUSE it equals the last one, so the last one IS the command');
    assert.match(second.record.output, /twice/, 'and its output is real');
  }, { profile: 'HISTCONTROL=ignoredups\n' });
});

// The other half, and the asymmetry is deliberate: ignorespace is how an
// operator hides a command carrying a secret, so its history entry is some
// EARLIER unrelated command. Naming it would attribute the hidden command's
// output to the wrong line — the one wrong answer worth paying an unnamed
// command to avoid.
test('a space-hidden command is NOT named under HISTCONTROL=ignorespace', opts, async () => {
  await withShell(async ({ exec, proc, passive }) => {
    await exec('echo visible');
    proc().write(' echo hidden\r');
    const got = await waitFor(() => passive.length > 0);
    assert.ok(got, 'ENTER: the hidden command was framed and reached the passive path');
    assert.strictEqual(passive[passive.length - 1].command, '',
      'borrowing `echo visible` as its name would label the hidden command\'s output');
  }, { profile: 'HISTCONTROL=ignorespace\n' });
});

// The same rule where the operator switched history off outright, and the one
// case a byte pin cannot reach: with history off NOTHING is ever added, so the
// last entry is whatever was loaded from their history FILE — an old command
// with no relationship to what is running now. Mutation-checked against a real
// bash: with the `-o history` clause deleted, an unrelated `date` sitting in the
// history file was reported as the command for two different `echo`s.
//
// The file has to be SEEDED for that to be observable. An empty history reports
// nothing either way, which is exactly how this survived a green suite.
test('a shell with history off does not borrow an old entry as the command name', opts, async () => {
  const hist = path.join(os.tmpdir(), `clodex-hist-${process.pid}-${Date.now()}`);
  fs.writeFileSync(hist, 'date\n');
  try {
    await withShell(async ({ exec }) => {
      // ENTER: the seeded entry is genuinely loaded and readable, so a shell
      // that named it would be reporting something real rather than nothing.
      const seeded = await exec('HISTTIMEFORMAT= builtin history 1');
      assert.match(seeded.record.output, /date/,
        'ENTER: the old entry is what `history 1` returns in this shell');
      const res = await exec('echo now');
      assert.strictEqual(res.record.command, '',
        'naming it `date` would attribute this command\'s output to an unrelated one');
      assert.match(res.record.output, /now/, 'the output is still captured and still real');
    }, { profile: 'set +o history\n', env: { HISTFILE: hist } });
  } finally {
    try { fs.rmSync(hist, { force: true }); } catch {}
  }
});

// HISTIGNORE IS A THIRD, INDEPENDENT SUPPRESSION CAUSE, and the reason it needs
// a test of its own is that `hc` cannot see it: it is not a HISTCONTROL token, so
// the two exclusions beside it both read as "not suppressed" and the guard names
// the PREVIOUS entry. HISTCONTROL is unset here deliberately, to leave HISTIGNORE
// as the only possible cause of what is measured.
//
// Downstream that borrowed name is worse than an empty one: foreignRecord vets
// ours-vs-operator by comparing the reported text, so the agent would be told
// `pwd` finished instead and its own command may never have run — a confident
// lie — while the firehose published this output under `pwd`.
//
// A PRIOR NAMED COMMAND is what makes the borrow observable at all. The harness
// gives every shell an empty HISTFILE, and an empty history names nothing either
// way — which is exactly how the `-o history` case survived a green suite until
// its history file was seeded.
test('a command skipped by HISTIGNORE does not borrow the previous entry', opts, async () => {
  await withShell(async ({ exec }) => {
    const prior = await exec('pwd');
    assert.strictEqual(prior.record.command, 'pwd',
      'ENTER: this shell names commands normally, so there IS a name available to borrow');
    const res = await exec('echo now');
    assert.strictEqual(res.record.command, '',
      'HISTIGNORE matches the command TEXT, which PS0 does not have — so it cannot be named');
    assert.strictEqual(res.record.exitCode, 0, 'the exit code is still right');
    assert.match(res.record.output, /now/, 'and the output is still captured');
  }, { profile: "unset HISTCONTROL\nHISTIGNORE='echo*'\n" });
});

// What the AGENT ends up being told when the shell genuinely cannot name it.
// The record is intact — right exit code, right output — and only the label is
// missing, which is exactly what v5.1.x threw the whole answer away for.
test('an unnamed record still carries a usable answer for the caller that asked', opts, async () => {
  await withShell(async ({ exec }) => {
    await exec('echo again');
    const res = await exec('echo again');
    assert.strictEqual(res.status, 'ok', `ENTER: it completed: ${JSON.stringify(res)}`);
    // ENTER: the whole point is the UNNAMED case, and a bash that named it
    // anyway would leave every assertion below true of the ordinary path — the
    // test would pass while measuring nothing this fix changed.
    assert.strictEqual(res.record.command, '',
      'ENTER: ignoreboth really did leave the command unnamed');
    assert.strictEqual(res.record.exitCode, 0, 'the exit code survived the missing name');
    assert.match(res.record.output, /again/, 'and so did the output');
    // engine.js's asked path, with the command it knows it sent.
    const text = formatCommand(res.record, { always: true, assumed: res.command });
    assert.strictEqual(text.split('\n')[0], '[terminal] echo again (assumed)',
      'the agent gets a named answer, marked on the line it quotes back');
    assert.match(text, /again/, 'with the output that used to be discarded');
    assert.match(text, /did not name the command/,
      'and the name is flagged as assumed rather than claimed as reported');
  }, { profile: 'HISTCONTROL=ignoreboth\n' });
});

// Dropping -l is what makes --rcfile work at all, and the generated rc puts the
// login startup back. Both halves are asserted: the reconstruction happened,
// and the known gap is REPORTED honestly rather than faked.
test('the reconstructed shell has login PATH but answers login_shell false', opts, async () => {
  await withShell(async ({ exec }) => {
    const res = await exec('shopt -q login_shell && echo LOGIN=yes || echo LOGIN=no');
    assert.match(res.record.output, /LOGIN=no/,
      'a reconstructed shell is NOT a login shell, and faking the flag would be worse');
  });
});

// /etc/profile is where the distro PATH comes from, and skipping it would gut
// the reason the tab spawned a login shell at all.
//
// The shell is given a DELIBERATELY BROKEN PATH to start from, because the
// obvious assertion — "/usr/bin is on PATH" — is true of a shell that inherited
// it from this process and never read /etc/profile at all. Mutation-checked:
// with the source removed, the inherited-PATH version still passed.
test('/etc/profile is really sourced, not merely named', opts, async () => {
  await withShell(async ({ exec }) => {
    const res = await exec('case ":$PATH:" in *:/usr/bin:*) echo HAS=yes;; *) echo HAS=no;; esac');
    assert.match(res.record.output, /HAS=(yes|no)/, 'ENTER: the probe ran and answered');
    assert.match(res.record.output, /HAS=yes/,
      'PATH started as /nonexistent, so only /etc/profile could have put /usr/bin back');
  }, { env: { PATH: '/nonexistent' } });
});

// The teardown's own regression test, and the reason reapPty escalates.
//
// A shell that ignores HUP survives node-pty's kill() forever. Before the
// escalation existed this did not fail loudly - the leaking test PASSED and the
// survivor held the runner's event loop open, so the suite hung at ~0% CPU with
// every assertion already green. `timeout` at the top of this file cannot catch
// that: it is per-test, and this test is not the one that would hang.
//
// So the property is asserted directly on the pid instead of on the runner's
// exit, which keeps it bounded and observable: withShell has returned, so its
// finally has run to completion, so the shell it spawned must be gone.
//
// This test cleans up its own subject unconditionally. A regression test for a
// process leak that leaks a process when it fails is worse than no test.
test('a shell that ignores SIGHUP is still gone once the teardown returns', opts, async () => {
  let pid = null;
  try {
    await withShell(async ({ exec, proc }) => {
      pid = proc() && proc().pid;
      // ENTER: without a live pid there is nothing to observe below, and
      // "the process is not alive" is trivially true of a shell that never
      // spawned - exactly the shape that passes while measuring nothing.
      assert.ok(pid && pidAlive(pid), 'ENTER: the shell is running before teardown');
      // ENTER: the trap has to be INSTALLED, not merely written to the
      // profile. A typo'd or unsourced profile would leave a plain shell that
      // dies on the first HUP, and this test would then pass against the very
      // teardown it exists to reject.
      const res = await exec('trap -p HUP');
      assert.match(res.record.output, /SIG_IGN|trap -- '' SIGHUP/,
        `ENTER: the shell really is ignoring HUP\n--- trap -p ---\n${res.record.output}`);
    }, { profile: "trap '' HUP\n" });

    assert.strictEqual(pidAlive(pid), false,
      `the teardown escalated past SIGHUP and reaped pid ${pid}; ` +
      'a survivor here holds the runner open and wedges the whole suite');
  } finally {
    // Belt and braces: if the assertion above failed, the survivor is still
    // running and would outlive this process as an orphan.
    if (pid && pidAlive(pid)) { try { process.kill(pid, 'SIGKILL'); } catch {} }
  }
});

// A machine with no usable bash would otherwise report a green file that
// measured nothing at all. Not skipped: the ABSENCE of a shell is a fact worth
// stating in the run, and CI on a box with only bash 3.2 should say so out loud
// rather than quietly pass.
test('the bash reporting property was measured against a real shell', () => {
  assert.ok(pty, 'node-pty is required for this file to mean anything');
  assert.ok(BASH, `no bash >= ${'4.4'} found in ${CANDIDATES.join(', ')} — nothing here was measured`);
});
