'use strict';
// term-shim.js — the generated zsh startup that emits OSC 133 marks.
//
// THIS FILE REACHES INTO THE OPERATOR'S SHELL STARTUP, which is the most
// intrusive thing Clodex does to a surface it does not own. Everything here is
// shaped by one rule: the operator's shell must behave EXACTLY as it does
// without us, and any failure of ours must degrade to a plain shell rather than
// to a broken one.
//
// The mechanism is ZDOTDIR (VSCode's approach): zsh reads its startup files from
// $ZDOTDIR when set, so we point it at a generated directory whose .zshrc
// sources the operator's real one and then adds two hooks. We do NOT edit any
// file the operator owns — nothing under their home is written, ever.
//
// Marks emitted, matching term-marks.js:
//   A  before each prompt        C;<b64>  a command started, with what ran
//   D;<status>  it finished
//
// Only zsh is shimmed. bash's equivalent is a different mechanism entirely
// (PROMPT_COMMAND + DEBUG trap, with its own well-known reentrancy traps) and a
// half-correct version that mangles a bash user's prompt is worse than not
// offering the feature. A non-zsh shell simply gets no marks and no shim.

const path = require('path');

function isZsh(shell) { return /(^|\/)zsh$/.test(String(shell || '')); }

// preexec's $1 is the line as typed — which is the point: the operator may have
// edited what was proposed, and what gets reported must be what actually ran.
// It is passed as a quoted argument to `printf '%s'`, so no expansion or
// splitting happens to it; base64 then makes its contents irrelevant to the
// mark's own framing. Do NOT reach for zsh's `${(q)...}` quoting operator here
// (measured against a real PTY): it ESCAPES the string, so `echo hello` arrives
// as `echo\ hello` and every reported command is subtly wrong.
//
// PRECMD IS PREPENDED, NOT APPENDED, and that ordering is the whole correctness
// of the capture window. precmd hooks run in array order before the prompt is
// drawn; a rc that sets its own precmd (OSC 7 cwd reporting is near-universal)
// would otherwise run FIRST and spray its bytes into the output attributed to
// the command that just finished — measured, it put an OSC 7 and a partial-line
// marker inside the captured output of every command. Ours running first closes
// the window before anything else can write. It also makes `$?` trustworthy:
// only the first hook sees the command's real status.
//
// preexec stays on add-zsh-hook (appended) because nothing is being captured at
// that moment, so order cannot corrupt anything.
//
// Both hooks are wrapped so a failure inside them cannot break the prompt:
// `builtin` bypasses any function shadowing `printf`, and `2>/dev/null` keeps a
// broken base64 from spraying stderr into the terminal on every command.
const HOOK_SNIPPET = `
# --- clodex terminal integration (OSC 133) -------------------------------
# Emits invisible semantic marks so Clodex can tell where a command's output
# begins and ends, and what it exited with. Remove the shim to disable.
if [[ -o interactive ]]; then
  __clodex_preexec() {
    local b
    b=$(builtin printf '%s' "$1" | base64 2>/dev/null | tr -d '\\n')
    builtin printf '\\033]133;C;%s\\007' "$b"
  }
  __clodex_precmd() {
    local s=$?
    builtin printf '\\033]133;D;%s\\007' "$s"
    builtin printf '\\033]133;A\\007'
    return $s
  }
  autoload -Uz add-zsh-hook 2>/dev/null && add-zsh-hook preexec __clodex_preexec
  # Guarded so re-sourcing this rc (a plugin manager, an operator's own
  # \`source ~/.zshrc\`) does not stack duplicate marks per prompt.
  if [[ -z "\${precmd_functions[(r)__clodex_precmd]}" ]]; then
    precmd_functions=(__clodex_precmd $precmd_functions)
  fi
fi
# --- end clodex terminal integration -------------------------------------
`;

// The generated .zshrc. Sourcing the operator's real file FIRST is not a style
// choice: their rc may set its own precmd/preexec, and add-zsh-hook appends
// rather than replacing, so running after them means both survive. Running
// before would let a plain `precmd() { ... }` assignment in their rc silently
// delete our hook.
//
// ZDOTDIR is restored to its previous value before their rc is sourced, because
// a plugin manager that re-derives paths from ZDOTDIR would otherwise look for
// the operator's plugins inside our generated directory.
function zshrcBody(realZdotdir) {
  const home = realZdotdir || '$HOME';
  return `# Generated by Clodex. Do not edit — rewritten on every terminal spawn.
# Restores the real ZDOTDIR before sourcing the operator's own startup, so
# nothing downstream resolves paths into this generated directory.
if [[ -n "\${__CLODEX_REAL_ZDOTDIR:-}" ]]; then
  export ZDOTDIR="$__CLODEX_REAL_ZDOTDIR"
else
  unset ZDOTDIR
fi
unset __CLODEX_REAL_ZDOTDIR
[[ -f "${home}/.zshrc" ]] && source "${home}/.zshrc"
${HOOK_SNIPPET}`;
}

// zsh reads .zshenv/.zprofile/.zlogin from ZDOTDIR too, so a shim directory
// containing only .zshrc would make a login shell SKIP the operator's own
// .zprofile — silently dropping PATH set there. Each generated file forwards to
// its counterpart. .zshrc is separate because it also carries the hooks.
const FORWARDED = ['.zshenv', '.zprofile', '.zlogin', '.zlogout'];
function forwardBody(file, realZdotdir) {
  const home = realZdotdir || '$HOME';
  return `# Generated by Clodex. Forwards to the operator's own ${file}.
[[ -f "${home}/${file}" ]] && source "${home}/${file}"
`;
}

// Build the shim directory and return the env additions, or null when the shell
// is not zsh / the write fails. Returning null must always be safe: the caller
// spawns an unshimmed shell and the operator gets a terminal with no marks,
// which is exactly what they had before this feature.
function buildZshShim({ dir, shell, env, fs: fsDep }) {
  const fs = fsDep || require('fs');
  if (!isZsh(shell)) return null;
  const src = env || {};
  // Their CURRENT ZDOTDIR, which is where their real rc lives. Captured before
  // we overwrite it, and passed through so the generated files can source the
  // right ones and hand it back.
  const real = src.ZDOTDIR || '';
  try {
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
    fs.writeFileSync(path.join(dir, '.zshrc'), zshrcBody(real), { mode: 0o600 });
    for (const f of FORWARDED) {
      fs.writeFileSync(path.join(dir, f), forwardBody(f, real), { mode: 0o600 });
    }
  } catch {
    return null;
  }
  return { ZDOTDIR: dir, __CLODEX_REAL_ZDOTDIR: real };
}

module.exports = { buildZshShim, isZsh, HOOK_SNIPPET, zshrcBody, forwardBody, FORWARDED };
