'use strict';
// term-shim.js — the generated shell startup that emits OSC 133 marks.
//
// THIS FILE REACHES INTO THE OPERATOR'S SHELL STARTUP, which is the most
// intrusive thing Clodex does to a surface it does not own. Everything here is
// shaped by one rule: the operator's shell must behave EXACTLY as it does
// without us, and any failure of ours must degrade to a plain shell rather than
// to a broken one.
//
// Marks emitted, matching term-marks.js:
//   A  before each prompt        C;<b64>  a command started, with what ran
//   D;<status>  it finished
//
// TWO SHELLS, TWO MECHANISMS, and they are not variations on each other:
//
//   zsh  — ZDOTDIR (VSCode's approach). Purely an ENV redirect: zsh reads its
//          startup from $ZDOTDIR when set, and it works for a LOGIN shell, so
//          the spawn argv is untouched.
//   bash — `--rcfile <generated>` and NO `-l`, because the two are mutually
//          exclusive (measured: a login bash ignores --rcfile entirely and
//          reads ~/.bash_profile). Purely an ARGV change, with the login
//          semantics reconstructed inside the generated file.
//
// That is why a builder returns { env, args } rather than an env map: bash
// cannot be shimmed without changing how the shell is spawned, and a seam that
// carried only env would write a correct file that bash never reads.
//
// We do NOT edit any file the operator owns — nothing under their home is
// written, ever, for either shell.

const path = require('path');

function isZsh(shell) { return /(^|\/)zsh$/.test(String(shell || '')); }
function isBash(shell) { return /(^|\/)bash$/.test(String(shell || '')); }

// preexec's $1 is the line as typed — which is the point: the operator may have
// edited what was proposed, and what gets reported must be what actually ran.
// It is passed as a quoted argument to `printf '%s'`, so no expansion or
// splitting happens to it; base64 then makes its contents irrelevant to the
// mark's own framing. Do NOT reach for zsh's `${(q)...}` quoting operator here
// (measured against a real PTY): it ESCAPES the string, so `echo hello` arrives
// as `echo\ hello` and every reported command is subtly wrong.
//
// PRECMD IS PREPENDED, NOT APPENDED, and that ordering is the whole correctness
// of the capture window. precmd hooks run in array order before the prompt is
// drawn; a rc that sets its own precmd (OSC 7 cwd reporting is near-universal)
// would otherwise run FIRST and spray its bytes into the output attributed to
// the command that just finished — measured, it put an OSC 7 and a partial-line
// marker inside the captured output of every command. Ours running first closes
// the window before anything else can write. It also makes `$?` trustworthy:
// only the first hook sees the command's real status.
//
// preexec stays on add-zsh-hook (appended) because nothing is being captured at
// that moment, so order cannot corrupt anything.
//
// Both hooks are wrapped so a failure inside them cannot break the prompt:
// `builtin` bypasses any function shadowing `printf`, and `2>/dev/null` keeps a
// broken base64 from spraying stderr into the terminal on every command.
const HOOK_SNIPPET = `
# --- clodex terminal integration (OSC 133) -------------------------------
# Emits invisible semantic marks so Clodex can tell where a command's output
# begins and ends, and what it exited with. Remove the shim to disable.
if [[ -o interactive ]]; then
  __clodex_preexec() {
    local b
    b=$(builtin printf '%s' "$1" | base64 2>/dev/null | tr -d '\\n')
    builtin printf '\\033]133;C;%s\\007' "$b"
  }
  __clodex_precmd() {
    local s=$?
    builtin printf '\\033]133;D;%s\\007' "$s"
    builtin printf '\\033]133;A\\007'
    return $s
  }
  autoload -Uz add-zsh-hook 2>/dev/null && add-zsh-hook preexec __clodex_preexec
  # Guarded so re-sourcing this rc (a plugin manager, an operator's own
  # \`source ~/.zshrc\`) does not stack duplicate marks per prompt.
  if [[ -z "\${precmd_functions[(r)__clodex_precmd]}" ]]; then
    precmd_functions=(__clodex_precmd $precmd_functions)
  fi
fi
# --- end clodex terminal integration -------------------------------------
`;

// The generated .zshrc. Sourcing the operator's real file FIRST is not a style
// choice: their rc may set its own precmd/preexec, and add-zsh-hook appends
// rather than replacing, so running after them means both survive. Running
// before would let a plain `precmd() { ... }` assignment in their rc silently
// delete our hook.
//
// ZDOTDIR is restored to its previous value before their rc is sourced, because
// a plugin manager that re-derives paths from ZDOTDIR would otherwise look for
// the operator's plugins inside our generated directory.
function zshrcBody(realZdotdir) {
  const home = realZdotdir || '$HOME';
  return `# Generated by Clodex. Do not edit — rewritten on every terminal spawn.
# Restores the real ZDOTDIR before sourcing the operator's own startup, so
# nothing downstream resolves paths into this generated directory.
if [[ -n "\${__CLODEX_REAL_ZDOTDIR:-}" ]]; then
  export ZDOTDIR="$__CLODEX_REAL_ZDOTDIR"
else
  unset ZDOTDIR
fi
unset __CLODEX_REAL_ZDOTDIR
[[ -f "${home}/.zshrc" ]] && source "${home}/.zshrc"
${HOOK_SNIPPET}`;
}

// zsh reads .zshenv/.zprofile/.zlogin from ZDOTDIR too, so a shim directory
// containing only .zshrc would make a login shell SKIP the operator's own
// .zprofile — silently dropping PATH set there. Each generated file forwards to
// its counterpart. .zshrc is separate because it also carries the hooks.
const FORWARDED = ['.zshenv', '.zprofile', '.zlogin', '.zlogout'];
function forwardBody(file, realZdotdir) {
  const home = realZdotdir || '$HOME';
  return `# Generated by Clodex. Forwards to the operator's own ${file}.
[[ -f "${home}/${file}" ]] && source "${home}/${file}"
`;
}

// Build the shim directory and return { env, args }, or null when the shell is
// not zsh / the write fails. Returning null must always be safe: the caller
// spawns an unshimmed shell and the operator gets a terminal with no marks,
// which is exactly what they had before this feature.
//
// `args` is `-l` — the same login shell the tab spawned before any of this
// existed. ZDOTDIR needs no argv change, so this half of the contract exists
// only because the bash builder below cannot say the same.
function buildZshShim({ dir, shell, env, fs: fsDep }) {
  const fs = fsDep || require('fs');
  if (!isZsh(shell)) return null;
  const src = env || {};
  // Their CURRENT ZDOTDIR, which is where their real rc lives. Captured before
  // we overwrite it, and passed through so the generated files can source the
  // right ones and hand it back.
  const real = src.ZDOTDIR || '';
  try {
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
    fs.writeFileSync(path.join(dir, '.zshrc'), zshrcBody(real), { mode: 0o600 });
    for (const f of FORWARDED) {
      fs.writeFileSync(path.join(dir, f), forwardBody(f, real), { mode: 0o600 });
    }
  } catch {
    return null;
  }
  return { env: { ZDOTDIR: dir, __CLODEX_REAL_ZDOTDIR: real }, args: ['-l'] };
}

// --- bash ----------------------------------------------------------------

// PS0 was added in bash 4.4, and without it there is no preexec at all — the
// shell emits D marks with no C before them, so term-marks never starts
// capturing and an agent's exec would wait for an ending that cannot come.
// Silence is the one outcome worse than refusing, so an older bash gets no
// shim. macOS still ships 3.2 as /bin/bash, which makes this the COMMON case
// on this platform rather than a defensive corner.
const BASH_MIN = [4, 4];

// `--norc --noprofile` because this runs on every terminal spawn: reading the
// operator's startup twice would double any side effect in it, and their rc is
// the slow part (measured ~10ms for the probe as written). Any failure — no
// such binary, a timeout, output that does not parse — answers null, which the
// caller reads as "not supported" and degrades on.
function defaultProbeVersion(shell) {
  try {
    const { execFileSync } = require('child_process');
    const out = execFileSync(shell, ['--norc', '--noprofile', '-c', 'echo ${BASH_VERSINFO[0]} ${BASH_VERSINFO[1]}'], { timeout: 2000, encoding: 'utf8' });
    const m = String(out).trim().match(/^(\d+)\s+(\d+)$/);
    return m ? [Number(m[1]), Number(m[2])] : null;
  } catch {
    return null;
  }
}

// Whether THIS bash can be shimmed, and what it turned out to be. Shared with
// the diagnosis message rather than duplicated there: two copies of the floor
// is how a supported shell starts being told it is unsupported.
function bashSupport({ shell, probeVersion }) {
  const v = (probeVersion || defaultProbeVersion)(shell);
  const ok = Array.isArray(v) && (v[0] > BASH_MIN[0] || (v[0] === BASH_MIN[0] && v[1] >= BASH_MIN[1]));
  return { ok, version: Array.isArray(v) ? v : null };
}

// THE HOOKS. Measured against a real bash 5.3 through a PTY, and every line
// below is one of those measurements — see the notes as you go.
//
// NO DEBUG TRAP. That mechanism is what made bash look unshimmable: it fires
// per SIMPLE command, so one `f` call in a 3-statement function produced six
// firings, and marking a command once from it means keeping a state machine in
// step with the shell's own recursion. PS0 is bash's actual preexec — expanded
// and printed ONCE, after the line is read and before it runs — so a compound
// command, a pipeline, a `&&` chain and a `for` loop each report exactly once,
// and an empty line reports nothing. It also leaves the operator's own DEBUG
// trap completely untouched, because we never install one.
//
// PROMPT_COMMAND IS PREPENDED, and it is the STRING form deliberately. Same
// reason as zsh's precmd prepend (ours must run before anything else can spray
// bytes into the captured output or destroy `$?`), and measured the same way:
// with the operator's `PROMPT_COMMAND='true'` set, prepending reported `false`
// as exit 1 while appending reported 0. bash 5.1+ also allows an ARRAY here,
// and the array form looks tidier, but assigning a STRING onto an existing
// array replaces element 0 and leaves the rest — so the string form composes
// correctly with both, while the array form silently drops the operator's
// command on 4.4–5.0 where PROMPT_COMMAND is scalar.
//
// THE COMMAND TEXT COMES FROM `history`, because there is no $BASH_COMMAND at
// PS0 time (measured: PS0 expanding it yields this hook's own printf). That is
// why the number is tracked: when a line is not added, a naive read reports the
// PREVIOUS command's text — measured, `echo first` was reported twice.
//
// WHY THE NUMBER ALONE IS NOT THE RULE. An unchanged number has causes that need
// opposite answers, and treating them alike made every REPEATED command unnamed
// on a stock ubuntu — which sets HISTCONTROL=ignoreboth in its default ~/.bashrc,
// reached through the profile this rc sources. Measured in
// ghcr.io/avirtual/clodex:5.1.1: a second `pwd` reported an empty payload, and
// clearing HISTCONTROL in the same shell reported it correctly.
//
//   ignoredups — the entry was suppressed BECAUSE it equals the last one, so the
//   last one IS the command. Naming it is correct. erasedups reaches the same
//   number by the other route: the entry IS added and an older duplicate is
//   deleted, so the count comes out unchanged — and again the last entry is this
//   command.
//   ignorespace, and history switched off — the last entry is some earlier,
//   unrelated command. Naming it would attribute this command's output to that
//   one.
//
// Those are indistinguishable at this point, so `ignoreboth` (ignoredups and
// ignorespace at once) must stay silent. That asymmetry is deliberate rather
// than conservative: ignorespace and `set +o history` are how an operator hides
// a command with a secret in it, and a stale label on THAT output is the one
// wrong answer worth paying an unnamed command to avoid.
//
// HISTIGNORE IS A THIRD CAUSE, CHECKED SEPARATELY, and it is not a HISTCONTROL
// token — measured on bash 5.3 with HISTCONTROL unset, `HISTIGNORE='ls*'` took
// the number from 2 to 3 across `pwd`, a skipped `ls -la`, and `echo hi`. Its
// patterns match the command's TEXT, which is exactly what is unavailable here,
// so there is no way to ask whether THIS command was the skipped one. Any
// HISTIGNORE at all therefore falls back to unnamed: reading a suppressed
// `ls -la` as the previous `pwd` is worse than saying nothing, because the exec
// path's foreignRecord compares the reported text and would tell the agent its
// command may never have run while publishing its output under the wrong name.
//
// An EMPTY payload still says "we do not know what ran" — term-marks treats an
// unnamed record as a real command with an unknown line, and formatCommand's
// `assumed` lets a caller that knows what it sent recover the answer.
//
// The static PS0 branch is not a nicety. With `shopt -u promptvars` bash does
// not expand a prompt, so a PS0 carrying a command substitution is printed
// LITERALLY on every command — measured, `$(__clodex_preexec)` on screen each
// time, which is precisely the mangled prompt this feature must never cause.
// The static form is pure backslash escapes, needs no expansion, and still
// frames the command; it just cannot say what the command was.
const BASH_HOOK_SNIPPET = `
# --- clodex terminal integration (OSC 133) -------------------------------
# Emits invisible semantic marks so Clodex can tell where a command's output
# begins and ends, and what it exited with. Remove the shim to disable.
if [[ $- == *i* && -z \${__clodex_installed:-} ]]; then
  __clodex_installed=1
  __clodex_hist=''
  __clodex_precmd() {
    local s=$?
    builtin printf '\\033]133;D;%s\\007' "$s"
    builtin printf '\\033]133;A\\007'
    # The history number as it stands BEFORE the next command is read, so the
    # preexec below can tell a new entry from a suppressed one.
    local h
    h=$(HISTTIMEFORMAT= builtin history 1 2>/dev/null)
    h=\${h#"\${h%%[![:space:]]*}"}
    __clodex_hist=\${h%%[[:space:]]*}
    return $s
  }
  __clodex_preexec() {
    local h n line b='' hc=":\${HISTCONTROL:-}:"
    h=$(HISTTIMEFORMAT= builtin history 1 2>/dev/null)
    h=\${h#"\${h%%[![:space:]]*}"}
    n=\${h%%[[:space:]]*}
    if [[ -n $n && -o history ]] && [[ $n != "$__clodex_hist" || ( -z \${HISTIGNORE:-} && $hc != *:ignorespace:* && $hc != *:ignoreboth:* ) ]]; then
      __clodex_hist=$n
      line=\${h#*[[:space:]]}
      line=\${line#"\${line%%[![:space:]]*}"}
      b=$(builtin printf '%s' "$line" | base64 2>/dev/null | tr -d '\\n')
    fi
    builtin printf '\\033]133;C;%s\\007' "$b"
  }
  # NO \\[ \\] AROUND EITHER FORM. They are a readline hint meaning "zero-width",
  # and readline only strips them from PS1, which it has to measure. PS0 is
  # printed by the shell after the line is accepted, so the pair is expanded to
  # literal SOH and STX and sent to the terminal — measured, two stray control
  # bytes landed at the head of every captured command's output. Nothing needs
  # them here: PS0 is never measured for cursor placement.
  #
  # EVERY EXPANSION IN THIS BLOCK IS :- DEFAULTED, including PS0's own, because an
  # operator profile running "set -u" turns an unset one into a fatal error: in
  # the function that would abort __clodex_preexec before its printf, so no C mark
  # is ever emitted and every exec ends timeout -> lost. PS0 is unset by default.
  # (No backticks in this file's shell comments — it is a JS template literal.)
  if shopt -q promptvars; then
    PS0='$(__clodex_preexec)'"\${PS0:-}"
  else
    PS0='\\e]133;C;\\a'"\${PS0:-}"
  fi
  PROMPT_COMMAND="__clodex_precmd\${PROMPT_COMMAND:+; \$PROMPT_COMMAND}"
fi
# --- end clodex terminal integration -------------------------------------
`;

// The generated rc. Everything above the hooks exists to put back what dropping
// `-l` took away, and NOT to improve on it:
//
//   /etc/profile FIRST — a real login bash reads it before anything in $HOME,
//   and on Linux it is where the distro's PATH comes from. Skipping it would
//   gut the reason the tab spawns a login shell at all.
//
//   Then the FIRST ONE THAT EXISTS of .bash_profile / .bash_login / .profile.
//   Not all three: bash stops at the first, and sourcing the others would run
//   startup the operator's own login shell never runs.
//
// ~/.bashrc IS DELIBERATELY ABSENT. `--rcfile` replaces it, and a login bash
// would not have read it either — the tab spawned `-l` before this, so
// profile-only IS the behaviour being matched. The common `.bash_profile`
// sources it anyway and it arrives transitively; adding it unconditionally
// would be a behaviour change dressed as a convenience.
//
// Their startup runs BEFORE the hooks for the same reason zsh's does: a
// PROMPT_COMMAND or PS0 they set must be visible to the prepend, and a plain
// assignment in their profile running afterwards would erase ours.
function bashrcBody() {
  return `# Generated by Clodex. Do not edit — rewritten on every terminal spawn.
# Reconstructs what a login bash reads, because --rcfile and -l are mutually
# exclusive: a login bash ignores this file entirely.
if [[ -r /etc/profile ]]; then
  source /etc/profile
fi
for __clodex_profile in "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.profile"; do
  if [[ -r "$__clodex_profile" ]]; then
    source "$__clodex_profile"
    break
  fi
done
unset __clodex_profile
${BASH_HOOK_SNIPPET}`;
}

// The bash counterpart of buildZshShim. Shares its directory (one shim dir per
// seat, cleaned up with the seat) but writes a single FILE inside it, since
// --rcfile names a file rather than a search path.
//
// Two ways to answer null here, and both are the standing degradation rule
// rather than an error path: a bash too old for PS0 (see BASH_MIN) and a write
// that failed. Either way the caller spawns the shell exactly as it did before
// this feature existed.
function buildBashShim({ dir, shell, fs: fsDep, probeVersion }) {
  const fs = fsDep || require('fs');
  if (!isBash(shell)) return null;
  if (!bashSupport({ shell, probeVersion }).ok) return null;
  const file = path.join(dir, 'bashrc');
  try {
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
    fs.writeFileSync(file, bashrcBody(), { mode: 0o600 });
  } catch {
    return null;
  }
  // No env additions at all — the whole mechanism is argv. The empty object is
  // deliberate rather than omitted: a caller spreading `shim.env` must not have
  // to special-case a shell that needs none.
  //
  // NO `-l`, and that is the point: with it, bash reads ~/.bash_profile and
  // never opens the file just written. The login semantics are inside that
  // file instead.
  return { env: {}, args: ['--rcfile', file, '-i'] };
}

// Why THIS shell cannot be shimmed, phrased for the operator, or null when it
// can be. Lives here rather than in the caller for the same reason the
// dispatcher does: the floor and the supported set are stated once, and a
// second copy is how a shell we do support starts being told it does not.
//
// The too-old-bash case earns its own sentence because it is the one an
// operator reaches without doing anything unusual, and a bare pair of version
// numbers reads as a bleeding-edge demand when it is the opposite: 4.4 is 2016
// and macOS is frozen at 3.2 from 2007, so the newest Mac fails exactly like
// the oldest. Both YEARS are load-bearing — drop them and the message tells an
// operator their machine is behind, which sends them to update something that
// cannot be updated. zsh is named FIRST because it needs no install (macOS
// default since 2019); demoting it back behind Homebrew turns a zero-step fix
// into a download.
function unsupportedShellReason({ shell, probeVersion }) {
  if (isZsh(shell)) return null;
  if (isBash(shell)) {
    const { ok, version } = bashSupport({ shell, probeVersion });
    if (ok) return null;
    const have = version ? `bash ${version.join('.')}` : 'a bash whose version could not be read';
    return `your terminal runs ${have}, and reporting needs bash ${BASH_MIN.join('.')} or newer (it uses PS0, added there) — not a bleeding-edge ask: 4.4 is from 2016, and macOS still ships 2007's 3.2 as /bin/bash, so the newest Mac reports the same version as the oldest. Nothing needs updating: make zsh your $SHELL — already there, the macOS default since 2019 — or a Homebrew bash if you prefer bash`;
  }
  return `your terminal runs ${shell || 'a shell Clodex does not shim'}, and only zsh and bash report command results back`;
}

// The one entry point the app uses. Dispatching here rather than in the caller
// keeps shell knowledge in this file: engine.js asks for a shim and gets one or
// null, and adding fish later does not touch it.
function buildTermShim(opts) {
  const shell = opts && opts.shell;
  if (isZsh(shell)) return buildZshShim(opts);
  if (isBash(shell)) return buildBashShim(opts);
  return null;
}

module.exports = {
  buildTermShim,
  buildZshShim,
  buildBashShim,
  bashSupport,
  unsupportedShellReason,
  isZsh,
  isBash,
  BASH_MIN,
  HOOK_SNIPPET,
  BASH_HOOK_SNIPPET,
  zshrcBody,
  bashrcBody,
  forwardBody,
  FORWARDED,
};
